# Spanish text for all 30 pages of Stella & Yakob v2

PAGES = [
    (1, [
        "El jardín de Stella estaba gris aquella tarde.",
        "Las flores inclinaban la cabeza.",
        "El cielo era pesado, como cargado de secretos.",
    ]),
    (2, [
        "A través de la ventana empañada,",
        "Stella oía hablar a sus padres.",
        "Palabras que no entendía.",
        "«Inteligencia artificial… IA…»",
    ]),
    (3, [
        "Stella se sentó en la hierba, abrazando sus rodillas.",
        "Una lágrima rodó por su mejilla.",
        "No sabía por qué algo le apretaba",
        "tan fuerte dentro del pecho.",
    ]),
    (4, [
        "Entonces el gran roble brilló suavemente.",
        "Y en la rama más alta,",
        "apareció un búho de ojos redondos y cálidos.",
        "«¿Por qué estás triste, querida?»",
    ]),
    (5, [
        "El búho inclinó la cabeza.",
        "Chispas doradas bailaron en el aire.",
        "«Me llamo Yakob.»",
        "«Y estoy aquí para ti.»",
    ]),
    (6, [
        "Stella lo miró.",
        "«Papá podría perder su trabajo»,",
        "dijo muy bajito.",
        "«Por culpa de esa cosa… la IA.»",
        "«Mamá lloró.»",
    ]),
    (7, [
        "Yakob desplegó sus grandes alas.",
        "Un polvo dorado giró a su alrededor.",
        "El jardín pareció temblar y transformarse.",
        "«Ven. Déjame mostrarte algo.»",
    ]),
    (8, [
        "Se encontraron en una cueva antigua.",
        "Manos humanas estaban pintadas en las paredes,",
        "ciervos, bisontes — apenas esbozados.",
        "«Crear», dijo Yakob, «es la magia de los humanos.»",
        "«Siempre lo ha sido.»",
    ]),
    (9, [
        "Las letras volaron como mariposas.",
        "Subieron muy alto en el cielo blanco.",
        "Stella atrapó una con la punta de los dedos.",
        "«La escritura cambió todo», dijo Yakob.",
        "«Las palabras pueden viajar a cualquier parte.»",
    ]),
    (10, [
        "Una bombilla dorada brilló en el centro.",
        "Stella y otro niño sostenían",
        "una cinta de luz de colores entre ellos.",
        "«Y la electricidad iluminó el mundo entero.»",
    ]),
    (11, [
        "Apareció un pequeño robot redondo y suave.",
        "A sus pies, pilas de dibujos:",
        "gatos, perros, conejos.",
        "«La IA aprende así», dijo Yakob.",
        "«Mira, una y otra vez.»",
    ]),
    (12, [
        "El robot agarró el dibujo de un perro…",
        "¡y lo puso en la pila de los gatos!",
        "Stella soltó una carcajada, tapándose la boca.",
        "Yakob inclinó la cabeza, divertido.",
        "«También se equivoca, ¿ves?»",
    ]),
    (13, [
        "Un médico sonrió a un niño pequeño.",
        "Un dron plantó una semilla en la tierra.",
        "«La IA ayuda a los médicos a curar»,",
        "dijo Yakob suavemente.",
        "«Y planta bosques donde ya no quedan.»",
    ]),
    (14, [
        "Stella se llevó la mano al pecho.",
        "«Pero… si las máquinas lo hacen todo»,",
        "susurró,",
        "«¿para qué sirven las personas?»",
        "Las luces a su alrededor se oscurecieron un poco.",
    ]),
    (15, [
        "Yakob bajó su gran cabeza hacia Stella.",
        "Sus ojos ámbar eran suaves y serios.",
        "«Esa es la verdadera pregunta», dijo.",
        "«Y no hay una respuesta fácil.»",
        "«Pero juntos podemos buscarla.»",
    ]),
    (16, [
        "Un hombre con sombrero de copa",
        "encendía un farol de gas.",
        "A su lado, una lámpara eléctrica se encendía sola.",
        "«Los faroleros desaparecieron»,",
        "dijo Yakob. «Pero la luz permaneció.»",
    ]),
    (17, [
        "De repente, una figura surgió de los arbustos.",
        "Un zorro elegante, de pelaje plateado.",
        "Sus ojos brillaban con una luz fría.",
        "Su sonrisa era demasiado amplia, demasiado perfecta.",
        "Stella retrocedió un paso.",
    ]),
    (18, [
        "El zorro giraba alrededor de Stella,",
        "su voz suave como la seda.",
        "«Conozco un atajo, pequeña.»",
        "«Ven conmigo — todo será más fácil.»",
        "Yakob observaba, con los ojos muy abiertos.",
    ]),
    (19, [
        "Un camino plateado se extendía ante ellas.",
        "Flores de cristal centelleaban en los bordes.",
        "A lo lejos, una torre de cristal brillaba.",
        "El zorro gesticuló con grandiosidad.",
        "Stella dio un paso adelante, vacilante.",
    ]),
    (20, [
        "Stella se detuvo.",
        "Bajó la vista.",
        "Bajo el brillo plateado,",
        "las flores reales estaban muertas.",
        "La tierra estaba agrietada y pálida.",
    ]),
    (21, [
        "Stella cruzó los brazos y miró al zorro.",
        "«Todo esto… ¿es real?»",
        "La sonrisa del zorro titubeó.",
        "En el reflejo de un charco,",
        "casi no tenía cara.",
    ]),
    (22, [
        "Stella plantó los pies en la tierra.",
        "«No, gracias», dijo claramente.",
        "El camino plateado se agrietó.",
        "El zorro se encogió, retrocedió hacia la niebla,",
        "y desapareció.",
    ]),
    (23, [
        "Yakob aterrizó suavemente junto a Stella.",
        "El jardín recuperó sus tonos dorados.",
        "Flores verdaderas crecieron a sus pies.",
        "«Supiste ver lo que era real»,",
        "dijo Yakob. «Ese es el mayor de los dones.»",
    ]),
    (24, [
        "Stella abrazó a Yakob con fuerza.",
        "Un arco iris se extendió suavemente sobre ellos.",
        "A lo lejos, unos niños reían.",
        "Una abuela contaba un cuento.",
        "«La IA nunca sentirá esto.»",
    ]),
    (25, [
        "Palabras luminosas bailaron alrededor de Stella:",
        "CURIOSIDAD — BONDAD",
        "VALENTÍA — CREATIVIDAD.",
        "Yakob planeó sobre ella en círculos lentos.",
        "«Estos son tus superpoderes.»",
    ]),
    (26, [
        "Por la ventana,",
        "papá estaba sentado con más calma.",
        "Una taza de té en las manos,",
        "una pequeña planta verde en el alféizar.",
        "«Papá también puede aprender»,",
        "dijo Stella. «Como yo.»",
    ]),
    (27, [
        "Mamá estaba rodeada de otros padres.",
        "Se mantenían en un círculo cálido,",
        "unidos por hilos de luz dorada.",
        "«Juntos como un bosque»,",
        "susurró Yakob.",
        "«Las raíces se tocan bajo la tierra.»",
    ]),
    (28, [
        "Stella puso su pequeña mano en el roble.",
        "Luciérnagas se encendieron a su alrededor.",
        "El cielo tomaba los rosas del amanecer.",
        "«Prometo hacer las preguntas correctas.»",
        "«Prometo seguir siendo curiosa.»",
    ]),
    (29, [
        "Stella caminó hacia la casa.",
        "En el umbral de la puerta,",
        "sus padres se tomaban de la mano.",
        "Se giró una última vez",
        "hacia el roble donde Yakob vigilaba.",
    ]),
    (30, [
        "La mañana había llegado.",
        "Stella pintaba en el jardín,",
        "el pincel lleno de colores.",
        "En la rama sobre ella,",
        "una pluma dorada brillaba suavemente.",
    ]),
]
