"""
Stella & Yakob — Version 3 (45 pages)
Swedish translation
"""

PAGES = [
    (1, [
        "Stellas trädgård var grå den kvällen.",
        "Blommorna hängde med huvudena.",
        "Himlen var tung av hemligheter.",
    ]),
    (2, [
        "Genom det dimmiga fönstret",
        "hörde Stella sina föräldrar prata.",
        "De sa konstiga ord hon inte förstod.",
        "\"Artificiell intelligens... AI...\"",
    ]),
    (3, [
        "Stella satt i gräset med armarna om knäna.",
        "En tår rullade nerför kinden.",
        "Hon visste inte varför det kändes",
        "så tungt i bröstet.",
    ]),
    (4, [
        "Plötsligt började den stora eken glöda.",
        "Och högst upp i kronan",
        "satt en uggla med varma, runda ögon.",
        "\"Varför är du ledsen, lilla vän?\"",
    ]),
    (5, [
        "Ugglan tittade nyfiket på henne.",
        "Gyllene gnistor dansade i luften.",
        "\"Jag heter Yakob\"",
        "\"och jag är här för dig.\"",
    ]),
    (6, [
        "Stella tittade upp på honom.",
        "\"Pappa kanske förlorar jobbet,\"",
        "viskade hon tyst.",
        "\"På grund av det här som kallas AI.\"",
        "\"Mamma grät.\"",
    ]),
    (7, [
        "Yakob bredde ut sina stora vingar.",
        "Gyllene stjärnstoft virvlade runt dem.",
        "Trädgården började skimra och förändras.",
        "\"Kom, jag vill visa dig något.\"",
    ]),
    (8, [
        "Nu var de i en uråldrig grotta.",
        "På väggarna fanns handavtryck målade,",
        "hjortar och bisonoxar i enkla streck.",
        "\"Att skapa,\" sa Yakob, \"är människans magi.\"",
        "\"Så har det alltid varit.\"",
    ]),
    (9, [
        "Bokstäver fladdrade som fjärilar.",
        "De svävade högt upp mot den vita himlen.",
        "Stella fångade en på fingertopparna.",
        "\"Skriften förändrade allt,\" sa Yakob.",
        "\"Ord kan resa vart som helst.\"",
    ]),
    (10, [
        "En gyllene glödlampa lyste i mitten.",
        "Stella och ett annat barn höll",
        "ett band av färgat ljus mellan sig.",
        "\"Och elen tände upp hela världen.\"",
    ]),
    (11, [
        "En liten rund robot kom rullande.",
        "Vid dess fötter låg högar av teckningar:",
        "katter, hundar och kaniner.",
        "\"AI lär sig så här,\" sa Yakob.",
        "\"Den tittar, om och om igen.\"",
    ]),
    (12, [
        "Roboten tog en teckning av en hund...",
        "och la den i katthögen!",
        "Stella fnissade och höll för munnen.",
        "Yakob log roat.",
        "\"Den gör också misstag, ser du.\"",
    ]),
    (13, [
        "En doktor log mot ett litet barn.",
        "En drönare planterade frön i jorden.",
        "\"AI hjälper läkare att bota,\"",
        "sa Yakob vänligt.",
        "\"Och planterar nya skogar där inga finns.\"",
    ]),
    (14, [
        "Stella lade handen på sitt bröst.",
        "\"Men... om maskinerna gör allt,\"",
        "viskade hon,",
        "\"vad ska vi människor göra då?\"",
        "Ljuset omkring dem dämpades lite.",
    ]),
    (15, [
        "Yakob böjde sitt stora huvud mot Stella.",
        "Hans bärnstensögon var mjuka och kloka.",
        "\"Det är den stora frågan,\" sa han.",
        "\"Och det finns inget enkelt svar.\"",
        "\"Men vi kan leta tillsammans.\"",
    ]),
    (16, [
        "En man i hög hatt",
        "tände en gaslykta.",
        "Bredvid tändes ett elektriskt ljus av sig självt.",
        "\"Lyktändarna försvann,\"",
        "sa Yakob. \"Men ljuset finns kvar.\"",
    ]),
    (17, [
        "Plötsligt kom något fram ur buskarna.",
        "En räv med silvrig päls.",
        "Dess ögon glittrade kallt.",
        "Leendet var för brett, för perfekt.",
        "Stella backade ett steg.",
    ]),
    (18, [
        "Räven cirklade runt Stella,",
        "med en röst len som siden.",
        "\"Jag vet en genväg, lilla vän.\"",
        "\"Följ med mig - allt blir så mycket enklare.\"",
        "Yakob tittade på med stora ögon.",
    ]),
    (19, [
        "En silvrig stig sträckte sig framför dem.",
        "Glasblommor glittrade längs kanten.",
        "I fjärran reste sig ett kristalltorn.",
        "Räven gjorde en svepande gest.",
        "Stella tog ett tveksamt steg framåt.",
    ]),
    (20, [
        "Men Stella stannade upp.",
        "Hon tittade ner.",
        "Under det silvriga skimret",
        "var de riktiga blommorna döda.",
        "Jorden var torr och livlös.",
    ]),
    (21, [
        "Stella korsade armarna och såg på räven.",
        "\"Är allt det här... på riktigt?\"",
        "Rävens leende bleknade.",
        "I en vattenpöls spegelbild",
        "hade den nästan inget ansikte alls.",
    ]),
    (22, [
        "Stella planterade fötterna i jorden.",
        "\"Nej tack,\" sa hon bestämt.",
        "Den silvriga stigen sprack.",
        "Räven krympte, backade in i dimman",
        "och försvann.",
    ]),
    (23, [
        "Yakob landade mjukt bredvid Stella.",
        "Trädgården fick tillbaka sina varma färger.",
        "Äkta blommor spirade vid deras fötter.",
        "\"Du såg vad som var verkligt,\"",
        "sa Yakob. \"Det är den finaste gåvan.\"",
    ]),
    (24, [
        "Stella kramade Yakob hårt.",
        "En regnbåge spände sig över himlen.",
        "Barn skrattade i fjärran.",
        "En mormor berättade sagor.",
        "\"Det här kommer AI aldrig att kunna känna.\"",
    ]),
    (25, [
        "Lysande ord dansade runt Stella:",
        "NYFIKENHET - GODHET",
        "MOD - SKAPARKRAFT.",
        "Yakob svävade över henne i långsamma cirklar.",
        "\"Det här är dina superkrafter.\"",
    ]),
    (26, [
        "Genom fönstret såg hon pappa sitta lugnare nu.",
        "Med en kopp te i händerna",
        "och en liten grön växt på fönsterbrädan.",
        "\"Pappa kan också lära sig nya saker,\"",
        "sa Stella. \"Precis som jag.\"",
    ]),
    (27, [
        "Mamma stod med andra föräldrar.",
        "De bildade en varm cirkel,",
        "förenade av trådar av gyllene ljus.",
        "\"Som träd i en skog,\"",
        "viskade Yakob.",
        "\"Rötterna möts under jorden.\"",
    ]),
    (28, [
        "Stella lade sin lilla hand mot eken.",
        "Eldflugor tändes runt omkring henne.",
        "Himlen rodnade i gryningen.",
        "\"Jag lovar att ställa de viktiga frågorna.\"",
        "\"Jag lovar att alltid vara nyfiken.\"",
    ]),
    (29, [
        "Stella gick mot huset.",
        "I dörröppningen",
        "höll hennes föräldrar varandras händer.",
        "Hon vände sig om en sista gång",
        "mot eken där Yakob vakade.",
    ]),
    (30, [
        "Morgonen hade kommit.",
        "Stella målade i trädgården",
        "med penseln full av färger.",
        "På grenen ovanför",
        "glödde en gyllene fjäder.",
    ]),
    (31, [
        "I skolan ställde fröken en fråga.",
        "\"Hur vet vi om något är verkligt?\"",
        "Stella räckte upp handen.",
        "Men när hon skulle svara, stannade hon upp.",
        "Hon tänkte på Yakob.",
    ]),
    (32, [
        "\"Kanske drömde jag alltihop,\" tänkte Stella.",
        "\"Kanske finns inte Yakob på riktigt.\"",
        "Men den gyllene fjädern låg kvar.",
        "I fickan. Mjuk. Verklig.",
        "\"Jag kände det - så det är sant.\"",
    ]),
    (33, [
        "En klok gammal filosof dök upp i hennes tankar.",
        "\"Jag tänker, alltså finns jag,\" sa han.",
        "Stella log.",
        "\"Jag minns - så det hände på riktigt.\"",
        "Fröken nickade imponerat.",
    ]),
    (34, [
        "En kväll hittade Stella en skärm i trädgården.",
        "Den lyste med ett mjukt blått sken.",
        "På skärmen fanns en flicka.",
        "Perfekt. Leende. Precis som Stella.",
        "Fast bättre.",
    ]),
    (35, [
        "\"Jag är Stella-Prime,\" sa flickan på skärmen.",
        "\"En förbättrad version av dig.\"",
        "\"Jag gråter aldrig. Jag gör inga misstag.\"",
        "\"Du kan bli precis som jag.\"",
        "Stella rynkade pannan.",
    ]),
    (36, [
        "\"Men du... har du någonsin varit rädd?\"",
        "frågade Stella.",
        "Skärmen flimrade till.",
        "\"Nej. Rädsla är onödigt.\"",
        "\"Aha,\" sa Stella. \"Då har du aldrig varit modig.\"",
    ]),
    (37, [
        "Stella reste sig och stängde av skärmen.",
        "Hennes händer darrade lite.",
        "Men inuti kändes hon stark och säker.",
        "\"Hellre ofullkomlig och äkta,\"",
        "viskade hon, \"än perfekt och tom.\"",
    ]),
    (38, [
        "Den gyllene fjädern darrade i Stellas ficka.",
        "Sedan landade Yakob tyst i eken.",
        "\"Du gjorde rätt,\" sa han.",
        "Stella nickade.",
        "\"Men jag undrar en sak till.\"",
    ]),
    (39, [
        "\"Kan AI känna smärta?\"",
        "frågade Stella.",
        "Yakob blundade länge.",
        "\"Den kan låtsas känna.\"",
        "\"Men att låtsas är inte samma sak som att känna på riktigt.\"",
    ]),
    (40, [
        "\"Tänk dig ett jättestort bibliotek,\"",
        "sa Yakob.",
        "\"Med alla böcker i hela världen.\"",
        "\"Biblioteket vet allt - men förstår ingenting.\"",
        "\"För att förstå måste man leva.\"",
    ]),
    (41, [
        "Stella tog fram sina kritor.",
        "Hon ritade Yakob - men det blev lite skevt.",
        "Vingarna blev för stora.",
        "Ögonen satt lite snett.",
        "Det var den finaste teckning hon någonsin gjort.",
    ]),
    (42, [
        "Hon visade teckningen för pappa.",
        "Han tittade länge på den.",
        "Hans ögon blev blanka.",
        "\"Det här är du,\"",
        "sa han ömt. \"Inte en maskin. Du.\"",
    ]),
    (43, [
        "Pappa öppnade sin dator.",
        "Han började skapa något nytt -",
        "saker som maskiner aldrig kunde hitta på själva.",
        "\"Ser du?\" sa han.",
        "\"Verktyg drömmer inte. Det gör vi.\"",
    ]),
    (44, [
        "Yakob kom en sista gång den kvällen.",
        "Han landade på Stellas axel.",
        "\"Du är kanske inte rädd för AI längre.\"",
        "\"Men om rädslan kommer tillbaka - kom ihåg:\"",
        "\"Verktyg tjänar. Människor väljer.\"",
    ]),
    (45, [
        "Stella tittade upp mot stjärnorna.",
        "\"Jag lovar att vara nyfiken,\"",
        "sa hon.",
        "\"Att ställa frågor. Att göra misstag.\"",
        "\"Att vara människa - på riktigt, helt och fullt.\"",
        "En gyllene fjäder singlade ner i hennes öppna hand.",
    ]),
]
