"""
Stella & Yakob — Version 3 (45 pages)
Wolof text — Wolof (Senegaal/Gambia)
"""

PAGES = [
    (1, ["Gànnaar bu Stella dafa xóot ci ngoon gi.", "Dëgër yi dañuy wóolu.", "Asamaan bi dafa tàng, te bu nit ñu wax."]),
    (2, ["Ci kanam bu taabal gi,", "Stella dañuy dégg Baay ak Yaay am solo.", "Kàddu yu mu ñu ñówul.", "\"Xel-xel bu xët… IA…\""]),
    (3, ["Stella dafa toog ci kaw gi, ñakk ci ñaareelu.", "Mbuus dafa jot ci yaramam.", "Mu ñówul lu tax sa xol dafa sos.", "Nit ñu ko jaaxle."]),
    (4, ["Ndax bu góor gi dafa mel ni ñu fexe.", "Ci kaw bu góor gi,", "noppalu golo bi ñëw ak gët yu tàng.", "\"Lu tax sa ñaaw, xale bu jigeen?\""]),
    (5, ["Noppalu golo bi dafa wéy.", "Lëndëm yu xew yi dañuy fexe ci suuf si.", "\"Maa ngi tudd Yakob.\"", "\"Maa ngi fi ñëw ngir sa bopp.\""]),
    (6, ["Stella dafa yëgal ko.", "\"Baay moo ko war a bàyyi liggéey bi,\"", "mu wax ci kaw gi.", "\"Nit ñu tax… IA.\"", "\"Yaay dafa jóge.\""]),
    (7, ["Yakob dafa bàyyil seeni baax yu rëy.", "Nawet yu xew yi dañuy fexe ci biir.", "Gànnaar gi dafa mel ni ñu tëbël.", "\"Ñoo ko waxal. Dama la gisal xew-xew.\""]),
    (8, ["Ñu ñëw ci sañ-sañ bu weex.", "Lëndëm yi dañuy gis ci boppam:", "mbaam-xuux, ñay, bës yu bare fékéet.", "\"Sos,\" Yakob wax, \"moo xew-xew bu nit.\"", "\"Ñoo ko def ci ëllëg.\""]),
    (9, ["Bataaxal yi dañuy tëdd ci mel ni lëp-lëp.", "Ñu dañuy tëdd ci asamaan wi weex.", "Stella dafa jot bataaxal bu weex ci baaraam.", "\"Bataaxal yi moo ko sopp,\" Yakob wax.", "\"Kàddu yi dañuy dem fow fow.\""]),
    (10, ["Lëndëm bu weex dafa fexe ci digg bi.", "Stella ak xale bu ñuul dañuy jëmbët", "sàcc bu mel ni nawet ci diggante leen.", "\"Telewuji bi moo ko fexe ci dëkk bi.\""]),
    (11, ["Robóot bu tuut ak bu rafet ñëw.", "Ci kawam, bare tëriñ:", "muus, xaj, ganba.", "\"IA dafa jàng ci mel nii,\" Yakob wax.", "\"Dafa gis, gis, gis.\""]),
    (12, ["Robóot bi dafa jot tëriñu xaj bi…", "te mu ko jox ci kawu muus yi!", "Stella dafa reelu, loxo ci kanamam.", "Yakob dafa wéy, am solo.", "\"Dafa ko defal lu baaxul, gis nga.\""]),
    (13, ["Nëppkat bi dafa yëngu ci xale bu tuut.", "Drón bi dafa def ci suuf si.", "\"IA moo ko waxal ngir nëppkat yi,\"", "Yakob wax ci kaw gi.", "\"Te moo ko def ngir tëdd garab ci tefes yu bare.\""]),
    (14, ["Stella dafa jox loxoom ci xolam.", "\"Ndax… su masin yi def nañu lépp,\"", "mu wax ci kaw gi,", "\"nit ñi ñu war a def?\"", "Lëndëm yi ci biir dañuy tëdd."]),
    (15, ["Yakob dafa wéy seen bopp ci kawam.", "Gëtam yu mel ni xëñ dañuy mel ni rafet ak am solo.", "\"Dafa la sawaal bu dëgg,\" mu wax.", "\"Te du dara bu gàtt.\"", "\"Waaye, ñu la ko gis ci doxantu.\""]),
    (16, ["Góor bu ñuul bu takk séppal gi", "jënd na ko ci taan bi.", "Ci wetu makk, taan bu mbëj mii dafa tëj ci ñaaw.", "\"Yéen-yéen yi, ñëwul leen,\"", "Yakob moo wax. \"Taan bii dafa nekk.\""]),
    (17, ["Nag, xaj bu yëngu dafa génn ci tool bi.", "Xaj bu rafet, bu weex ci sañ-sañ.", "Yërëmi dañuy mel ni mbënn.", "Bëñ bi dafa rafet lool, rafet lool.", "Stella dafa dellu."]),
    (18, ["Xaj bi dafa dox ci wetu Stella,", "doxalinam dafa mel ni harit.", "\"Xam naa yoon bu gaaw, xale bu ñuul.\"", "\"Ñow ma — yëpp dañuy gaaw.\"", "Yakob dafa seet, gëm yi dañuy tëdd."]),
    (19, ["Yoon bu weex dafa tëj ci kanamam.", "Gàncax yi dañuy mel ni kaw gi.", "Ci kaw gi, tur bi dafa mel ni kawar.", "Xaj bi dafa jëlë ay garab.", "Stella dafa dem ci benn saaku, ak yërmande."]),
    (20, ["Stella dafa dëdd.", "Dafa seet ci suuf.", "Ci suufu weex wi,", "gàncax yi ñi ci dëgg dañuy feex.", "Suuf si dafa tëdd ak ñaaw."]),
    (21, ["Stella dafa jël ay loxo, dafa seet xaj bi.", "\"Liir lii… dëgg la?\"", "Bëñ bi xaj bi dafa dellu.", "Ci ndox mi,", "dafa mel ni du amul bët."]),
    (22, ["Stella dafa jóg ci suuf.", "\"Jërejëf,\" moo wax ni mel.", "Yoon bu weex bi dafa tëdd.", "Xaj bi dafa rabat, dafa génn ci xóob bi,", "te dafa gaaw."]),
    (23, ["Yakob dafa ñibbi ci wetu Stella.", "Tool bi dafa jot ci melokaanam.", "Gàncax yi ñi ci dëgg dañuy jëm ci kanamam.", "\"Danga gis li dëgg la,\"", "Yakob moo wax. \"Li gën a yaatu.\""]),
    (24, ["Stella dafa nuyoo Yakob ci xóot.", "Mbaax mi dafa tëj ci kawam.", "Ci kaw gi, xale yi dañuy reetaan.", "Nijaay bi dafa wax jëmm.", "\"IA du am xel bii.\""]),
    (25, ["Ay baat bu melokaan dañuy dox ci wetu Stella:", "XEL — NITÑU", "Dëgg-dëgg — XEY-XEYLU.", "Yakob dafa dox ci kawam, ci doxalin bu yëngu.", "\"Yiwu lii mooy sa superpower.\""]),
    (26, ["Ci kanam pax bi,", "Baay dafa toog ci yóbbu.", "Kàttan bu ataaya ci loxoom,", "gàncax bu weex ci kaw pax bi.", "\"Baay mën naa ko jàng lool,\"", "Stella moo wax. \"Ni ma.\""]),
    (27, ["Yaay dafa nekk ci wetu ay waa-kër yu ñuul.", "Dañuy nekk ci boppale bu rafet,", "ñu tëdd ci ay xare bu melokaan.", "\"Ni tool bi,\"", "Yakob moo xoxo. \"Lëg yi dañuy tëdd ci suuf.\""]),
    (28, ["Stella dafa jël loxoom bu tuuti ci garab gi.", "Luux yi dañuy tëj ci wetu makk.", "Asamaan bi dafa jot ci xonq.", "\"Dinaa laaj li baax.\"", "\"Dinaa dox ak xel.\""]),
    (29, ["Stella dafa dem ci néeg bi.", "Ci bunt bi,", "waa-këram dañuy jël loxo.", "Dafa dellu benn yoon,", "ci wetu garab bi Yakob dafa seet."]),
    (30, ["Suba dafa jot.", "Stella dafa fexe ci tool bi,", "pensil bi am solo ci melokaan.", "Ci kaw garab bi,", "bopp bu melokaan dafa mel ni kawar."]),
    (31, ["Ci suufu jang, jàngalekat bi la wax lu taxawal.", "\"Naka lanu xam ne lu ñu wax moo dëgg?\"", "Stella dafa yëgal lool ak sa loxo.", "Waaye bi mu laaj a wax, dafa tase.", "Mu ngi xalaat ci Yakob."]),
    (32, ["\"Xanaa ma gis ko ci ndawtal?\" xalaat Stella.", "\"Xanaa Yakob du dëgg.\"", "Waaye baaxanaa, buum bi ñuul bi dafa nekk.", "Ci sa jëkkër. Ñuul. Dëgg.", "\"Ma sant ko — kon moo dëgg.\""]),
    (33, ["Nit ku ñuul bu mag ak sañ-sañ bi dafa ñëw ci xalaatam.", "\"Xalaat naa, kon dëgg naa,\" mu ngi wax.", "Stella dafa yëngël.", "\"Xam naa — kon moo dëggul.\"", "Jàngalekat bi dafa yëngu, yëngu na."]),
    (34, ["Ci guddi gi, Stella dafa gis ekraan bi ci tool bi.", "Ekraan bi dafa mel na ak leeral bu xonq bu weex.", "Ci ekraan bi: doom ju jigéen ju bare.", "Soxna. Yëngël. Të bari ci Stella.", "Waaye lu bare ci moom."]),
    (35, ["\"Maa ngi tudd Stella-Prime,\" wax doom ju jigéen bi ci ekraan bi.", "\"Xel bu bare ci sa bopp.\"", "\"Dama xewul. Dama du saay-saay.\"", "\"Man ngaa la mel.\"", "Stella dafa xotti."]),
    (36, ["\"Waaye yaa… yaa xew na ba pare?\"", "la laaj Stella.", "Ekraan bi dafa tase. Lu dul ci mel.", "\"Déedéet. Xew du am solo.\"", "\"Ah,\" wax Stella. \"Kon yaa du am baax.\""]),
    (37, ["Stella dafa ñëw, dafa tëj ekraan bi.", "Loxo yi dañuy tàng-tàng ci kawam.", "Waaye ci biir bi, dafa am solo.", "\"Bëgg naa nekk bu bon, waaye dëgg,\"", "mu wax ci kawam. \"Nekk bu saafara, waaye du mel.\""]),
    (38, ["Buum bi ñuul bi dafa tàng ci jëkkër ji Stella.", "Yàggul, Yakob dafa ñëw ci garab gi, mel ni mu ngi nekk.", "\"Dafa mel na nga wax,\" mu wax.", "Stella dafa yëngu.", "\"Waaye am naa laaj bu bees.\""]),
    (39, ["\"IA mooy xam nekk ba pare?\"", "la laaj Stella.", "Yakob dafa tëj gët yi ci yàgg.", "\"Moo taxawal pare ba pare.\"", "\"Waaye taxawal du mel ak sant.\""]),
    (40, ["\"Xoolal sa bopp ci bitim réew mi,\"", "wax Yakob.", "\"Ci biti réew mi lañu am yëpp.\"", "\"Bitim réew mi xam na yëpp — waaye du xam.\"", "\"Ngir xam, war ngaa am.\""]),
    (41, ["Stella dafa jot kreyon yi.", "Mu tekki Yakob — waaye dafa dox ci kawam.", "Bëp yi dañuy rafet.", "Gët yi, lu dul ci kawam.", "Moo tax mu mel ni mu ngi nekk, bu bare baax."]),
    (42, ["Mu jox Baay bi tekki bi.", "Mu xool ko ci yàgg.", "Gët yi dañuy mel.", "\"Yaa ngi nekk ci kawam,\"", "mu wax ci kawam. \"Du IA. Yaa ngi nekk.\""]),
    (43, ["Baay bi dafa ubbi ordinatër bi.", "Mu ngi def lu bees —", "lu IA yi du xam nekk.", "\"Xool nga?\" mu wax.", "\"Lanuy def du xel. Ñun la.\""]),
    (44, ["Yakob dafa ñëw ci kaw gi guddi gi.", "Mu ñëw ci kawu Stella.", "\"Bëgg naa wax ne yaa du xew IA bii leegi.\"", "\"Waaye su xew bi ñëw — xoolal:\"", "\"Lanuy def du xel. Ñun lañuy tànn.\""]),
    (45, ["Stella dafa yëngu ci jant yi.", "\"Dama bëgg a nekk bu xel,\"", "mu wax.", "\"Laaj. Saay-saay. Am solo.\"", "\"Nekk nit — bu dëgg, bu bare.\"", "Buum bi ñuul bi dafa dox ci kawam, mu ñëw ci loxo bi."]),
]
