# English text for all 30 pages of Stella & Yakob v2

PAGES = [
    (1, [
        "Stella's garden was grey that evening.",
        "The flowers hung their heads.",
        "The sky was heavy, as if full of secrets.",
    ]),
    (2, [
        "Through the misty window,",
        "Stella could hear her parents talking.",
        "Words she didn't understand.",
        "\"Artificial intelligence… AI…\"",
    ]),
    (3, [
        "Stella sat in the grass, hugging her knees.",
        "A tear rolled down her cheek.",
        "She didn't know why something squeezed",
        "so tight inside her chest.",
    ]),
    (4, [
        "Then the great oak glowed softly.",
        "And on the highest branch,",
        "an owl appeared with round, warm eyes.",
        "\"Why are you sad, my dear?\"",
    ]),
    (5, [
        "The owl tilted his head.",
        "Golden sparks danced in the air.",
        "\"My name is Yakob.\"",
        "\"And I am here for you.\"",
    ]),
    (6, [
        "Stella looked up at him.",
        "\"Papa might lose his job,\"",
        "she said very quietly.",
        "\"Because of this thing… AI.\"",
        "\"Mama cried.\"",
    ]),
    (7, [
        "Yakob spread his great wings.",
        "Golden dust swirled around them.",
        "The garden seemed to shiver and change.",
        "\"Come. Let me show you something.\"",
    ]),
    (8, [
        "They found themselves in an ancient cave.",
        "Human hands were painted on the walls,",
        "deer, bison — barely sketched.",
        "\"To create,\" said Yakob, \"is the magic of humans.\"",
        "\"It always has been.\"",
    ]),
    (9, [
        "Letters took flight like butterflies.",
        "They rose high into the white sky.",
        "Stella caught one at her fingertips.",
        "\"Writing changed everything,\" said Yakob.",
        "\"Words can travel anywhere.\"",
    ]),
    (10, [
        "A golden lightbulb glowed at the centre.",
        "Stella and another child held",
        "a ribbon of coloured light between them.",
        "\"And electricity lit up the whole world.\"",
    ]),
    (11, [
        "A small, round, gentle robot appeared.",
        "At its feet, stacks of drawings:",
        "cats, dogs, rabbits.",
        "\"AI learns like this,\" said Yakob.",
        "\"It watches, again and again.\"",
    ]),
    (12, [
        "The robot grabbed a drawing of a dog…",
        "and placed it in the cats pile!",
        "Stella burst out laughing, hand over her mouth.",
        "Yakob tilted his head, amused.",
        "\"It makes mistakes too, you see.\"",
    ]),
    (13, [
        "A doctor smiled at a small child.",
        "A drone planted a seed in the earth.",
        "\"AI helps doctors heal,\"",
        "said Yakob gently.",
        "\"And plants forests where none remain.\"",
    ]),
    (14, [
        "Stella placed her hand on her chest.",
        "\"But… if machines do everything,\"",
        "she whispered,",
        "\"what are people for?\"",
        "The lights around them dimmed a little.",
    ]),
    (15, [
        "Yakob lowered his great head toward Stella.",
        "His amber eyes were soft and serious.",
        "\"That is the real question,\" he said.",
        "\"And there is no easy answer.\"",
        "\"But together, we can look.\"",
    ]),
    (16, [
        "A man in a top hat",
        "was lighting a gas lamp.",
        "Beside him, an electric light turned on by itself.",
        "\"The lamplighters disappeared,\"",
        "said Yakob. \"But the light remained.\"",
    ]),
    (17, [
        "Suddenly, a shape burst from the bushes.",
        "A sleek fox, with silver fur.",
        "Its eyes glittered with a cold light.",
        "Its smile was too wide, too perfect.",
        "Stella stepped back.",
    ]),
    (18, [
        "The fox circled around Stella,",
        "its voice smooth as silk.",
        "\"I know a shortcut, little one.\"",
        "\"Come with me — everything will be simpler.\"",
        "Yakob watched, eyes wide open.",
    ]),
    (19, [
        "A silver path stretched out before them.",
        "Glass flowers sparkled along the edges.",
        "In the distance, a crystal tower glittered.",
        "The fox gestured grandly.",
        "Stella took one step forward, hesitant.",
    ]),
    (20, [
        "Stella stopped.",
        "She looked down.",
        "Beneath the silver shimmer,",
        "the real flowers were dead.",
        "The earth was cracked and pale.",
    ]),
    (21, [
        "Stella crossed her arms and looked at the fox.",
        "\"Is all of this… real?\"",
        "The fox's smile faltered.",
        "In the reflection of a puddle,",
        "it had almost no face at all.",
    ]),
    (22, [
        "Stella planted her feet in the earth.",
        "\"No thank you,\" she said clearly.",
        "The silver path cracked.",
        "The fox shrank, retreated into the mist,",
        "and vanished.",
    ]),
    (23, [
        "Yakob landed softly beside Stella.",
        "The garden found its golden colours again.",
        "Real flowers grew at their feet.",
        "\"You could see what was real,\"",
        "said Yakob. \"That is the greatest gift.\"",
    ]),
    (24, [
        "Stella hugged Yakob tight.",
        "A rainbow stretched gently above them.",
        "In the distance, children were laughing.",
        "A grandmother told a story.",
        "\"AI will never feel this.\"",
    ]),
    (25, [
        "Glowing words danced around Stella:",
        "CURIOSITY — KINDNESS",
        "COURAGE — CREATIVITY.",
        "Yakob soared above her in slow circles.",
        "\"These are your superpowers.\"",
    ]),
    (26, [
        "Through the window,",
        "Papa was sitting more calmly.",
        "A cup of tea in his hands,",
        "a small green plant on the sill.",
        "\"Papa can learn too,\"",
        "said Stella. \"Just like me.\"",
    ]),
    (27, [
        "Mama was surrounded by other parents.",
        "They stood in a warm circle,",
        "joined by threads of golden light.",
        "\"Together like a forest,\"",
        "whispered Yakob.",
        "\"The roots touch beneath the earth.\"",
    ]),
    (28, [
        "Stella placed her small hand on the oak.",
        "Fireflies lit up around her.",
        "The sky was taking on the rose of dawn.",
        "\"I promise to ask the right questions.\"",
        "\"I promise to stay curious.\"",
    ]),
    (29, [
        "Stella walked toward the house.",
        "In the doorway,",
        "her parents were holding hands.",
        "She turned one last time",
        "toward the oak where Yakob kept watch.",
    ]),
    (30, [
        "Morning had come.",
        "Stella was painting in the garden,",
        "her brush full of colours.",
        "On the branch above her,",
        "a golden feather glowed softly.",
    ]),
]
