"""
Stella & Yakob — Version 3 (45 pages)
Polish translation
"""

PAGES = [
    (1, [
        "Ogród Stelli był szary tego wieczoru.",
        "Kwiaty pochyliły główki.",
        "Niebo było ciężkie, jakby pełne tajemnic.",
    ]),
    (2, [
        "Przez zaparowane okno",
        "Stella słyszała rozmowę rodziców.",
        "Padały słowa, których nie rozumiała.",
        "\"Sztuczna inteligencja... SI...\"",
    ]),
    (3, [
        "Stella siedziała na trawie, obejmując kolana.",
        "Po policzku spłynęła jej łza.",
        "Nie wiedziała, dlaczego czuje",
        "taki ucisk w sercu.",
    ]),
    (4, [
        "Nagle wielki dąb zaczął delikatnie świecić.",
        "A na najwyższej gałęzi",
        "pojawiła się sowa o ciepłych, okrągłych oczach.",
        "\"Czemu jesteś smutna, kochanie?\"",
    ]),
    (5, [
        "Sowa przekrzywiła główkę.",
        "W powietrzu tańczyły złote iskierki.",
        "\"Mam na imię Jakub.\"",
        "\"I jestem tu dla ciebie.\"",
    ]),
    (6, [
        "Stella spojrzała na niego.",
        "\"Tata może stracić pracę,\"",
        "wyszeptała cichutko.",
        "\"Przez tę... SI.\"",
        "\"Mama płakała.\"",
    ]),
    (7, [
        "Jakub rozłożył swoje wielkie skrzydła.",
        "Wokół nich wirował złoty pył.",
        "Ogród jakby zadrżał i zaczął się zmieniać.",
        "\"Chodź. Coś ci pokażę.\"",
    ]),
    (8, [
        "Znaleźli się w pradawnej jaskini.",
        "Na ścianach widniały odciski ludzkich dłoni,",
        "szkice jeleni i bizonów.",
        "\"Tworzenie,\" powiedział Jakub, \"to ludzka magia.\"",
        "\"Zawsze tak było.\"",
    ]),
    (9, [
        "Literki unosiły się jak motylki.",
        "Wzlatywały wysoko w białe niebo.",
        "Stella złapała jedną na czubkach palców.",
        "\"Pismo wszystko zmieniło,\" powiedział Jakub.",
        "\"Słowa mogą wędrować wszędzie.\"",
    ]),
    (10, [
        "W środku świeciła złota żarówka.",
        "Stella i inne dziecko trzymały",
        "wstążkę kolorowego światła między sobą.",
        "\"A elektryczność rozjaśniła cały świat.\"",
    ]),
    (11, [
        "Pojawił się maleńki, okrąglutki robot.",
        "U jego stóp leżały stosy rysunków:",
        "kotki, pieski, króliczki.",
        "\"SI uczy się właśnie tak,\" wyjaśnił Jakub.",
        "\"Patrzy i patrzy, wciąż od nowa.\"",
    ]),
    (12, [
        "Robot chwycił rysunek psa...",
        "i włożył go do stosu z kotami!",
        "Stella zachichotała, zasłaniając usta.",
        "Jakub przekrzywił głowę rozbawiony.",
        "\"Widzisz? On też się myli.\"",
    ]),
    (13, [
        "Lekarz uśmiechał się do małego dziecka.",
        "Dron sadził nasionko w ziemi.",
        "\"SI pomaga lekarzom leczyć,\"",
        "powiedział łagodnie Jakub.",
        "\"I sadzi lasy tam, gdzie ich brakuje.\"",
    ]),
    (14, [
        "Stella położyła rękę na sercu.",
        "\"Ale... jeśli maszyny robią wszystko,\"",
        "wyszeptała,",
        "\"po co są ludzie?\"",
        "Światła wokół nich przygasły.",
    ]),
    (15, [
        "Jakub pochylił swoją wielką głowę ku Stelli.",
        "Jego bursztynowe oczy były łagodne i poważne.",
        "\"To bardzo ważne pytanie,\" powiedział.",
        "\"I nie ma na nie prostej odpowiedzi.\"",
        "\"Ale razem możemy jej poszukać.\"",
    ]),
    (16, [
        "Mężczyzna w cylindrze",
        "zapalał latarnię gazową.",
        "Obok niego sama zapaliła się elektryczna.",
        "\"Latarnicy zniknęli,\"",
        "powiedział Jakub. \"Ale światło zostało.\"",
    ]),
    (17, [
        "Nagle z krzaków wyłonił się kształt.",
        "Smukły lis o srebrnym futerku.",
        "Jego oczy lśniły zimnym blaskiem.",
        "Uśmiech miał zbyt szeroki, zbyt idealny.",
        "Stella cofnęła się.",
    ]),
    (18, [
        "Lis krążył wokół Stelli,",
        "jego głos był gładki jak jedwab.",
        "\"Znam skrót, maleńka.\"",
        "\"Chodź ze mną — wszystko będzie prostsze.\"",
        "Jakub patrzył szeroko otwartymi oczami.",
    ]),
    (19, [
        "Przed nimi rozciągała się srebrzysta ścieżka.",
        "Po bokach lśniły szklane kwiaty.",
        "W oddali błyszczała kryształowa wieża.",
        "Lis wykonał szeroki gest.",
        "Stella niepewnie zrobiła krok do przodu.",
    ]),
    (20, [
        "Stella zatrzymała się.",
        "Spojrzała w dół.",
        "Pod srebrnym połyskiem",
        "prawdziwe kwiaty były martwe.",
        "Ziemia była spękana i blada.",
    ]),
    (21, [
        "Stella skrzyżowała ręce i spojrzała na lisa.",
        "\"Czy to wszystko... jest prawdziwe?\"",
        "Uśmiech lisa zbladł.",
        "W odbiciu kałuży",
        "prawie nie miał twarzy.",
    ]),
    (22, [
        "Stella mocno wbiła stopy w ziemię.",
        "\"Nie, dziękuję,\" powiedziała stanowczo.",
        "Srebrna ścieżka pękła.",
        "Lis skulił się, cofnął we mgłę",
        "i zniknął.",
    ]),
    (23, [
        "Jakub wylądował miękko obok Stelli.",
        "Ogród znów nabrał złotych barw.",
        "U ich stóp rosły prawdziwe kwiaty.",
        "\"Potrafiłaś rozpoznać, co jest prawdziwe,\"",
        "powiedział Jakub. \"To największy dar.\"",
    ]),
    (24, [
        "Stella mocno przytuliła Jakuba.",
        "Nad nimi delikatnie rozpościerała się tęcza.",
        "Z oddali dobiegał śmiech dzieci.",
        "Babcia opowiadała historię.",
        "\"SI nigdy tego nie poczuje.\"",
    ]),
    (25, [
        "Świecące słowa tańczyły wokół Stelli:",
        "CIEKAWOŚĆ — ŻYCZLIWOŚĆ",
        "ODWAGA — KREATYWNOŚĆ.",
        "Jakub zataczał nad nią powolne kręgi.",
        "\"To są twoje supermoce.\"",
    ]),
    (26, [
        "Przez okno widziała tatę,",
        "który siedział spokojniej.",
        "Trzymał filiżankę herbaty,",
        "a na parapecie stała mała roślinka.",
        "\"Tata też może się uczyć,\"",
        "powiedziała Stella. \"Tak jak ja.\"",
    ]),
    (27, [
        "Mama stała wśród innych rodziców.",
        "Tworzyli ciepły krąg,",
        "połączony złotymi nićmi światła.",
        "\"Razem jak las,\"",
        "szepnął Jakub.",
        "\"Korzenie splatają się pod ziemią.\"",
    ]),
    (28, [
        "Stella położyła małą dłoń na dębie.",
        "Wokół niej rozbłysły świetliki.",
        "Niebo nabierało różowego koloru świtu.",
        "\"Obiecuję zadawać właściwe pytania.\"",
        "\"Obiecuję być zawsze ciekawa.\"",
    ]),
    (29, [
        "Stella ruszyła w stronę domu.",
        "W drzwiach",
        "jej rodzice trzymali się za ręce.",
        "Obejrzała się jeszcze raz",
        "na dąb, gdzie czuwał Jakub.",
    ]),
    (30, [
        "Nastał poranek.",
        "Stella malowała w ogrodzie,",
        "jej pędzelek pełen kolorów.",
        "Na gałęzi nad nią",
        "delikatnie świeciło złote piórko.",
    ]),
    (31, [
        "W szkole nauczyciel zadał pytanie.",
        "\"Skąd wiemy, że coś jest prawdziwe?\"",
        "Stella od razu podniosła rękę.",
        "Ale gdy szukała słów, zawahała się.",
        "Pomyślała o Jakubie.",
    ]),
    (32, [
        "\"Może mi się to przyśniło,\" pomyślała Stella.",
        "\"Może Jakub nie jest prawdziwy.\"",
        "Ale złote piórko wciąż tam było.",
        "W jej kieszeni. Miękkie. Prawdziwe.",
        "\"Czułam to — więc to prawda.\"",
    ]),
    (33, [
        "W jej głowie pojawił się stary filozof z brodą.",
        "\"Myślę, więc jestem,\" mówił.",
        "Stella się uśmiechnęła.",
        "\"Pamiętam — więc to naprawdę się wydarzyło.\"",
        "Nauczyciel kiwnął głową ze zdziwieniem.",
    ]),
    (34, [
        "Pewnego wieczoru Stella znalazła w ogrodzie ekran.",
        "Świecił delikatnym niebieskim światłem.",
        "Na ekranie była mała dziewczynka.",
        "Idealna. Uśmiechnięta. Zupełnie jak Stella.",
        "Tylko że lepsza.",
    ]),
    (35, [
        "\"Jestem Stella-Prime,\" powiedziała dziewczynka z ekranu.",
        "\"Ulepszona wersja ciebie.\"",
        "\"Nigdy nie płaczę. Nigdy się nie mylę.\"",
        "\"Mogłabyś być taka jak ja.\"",
        "Stella zmarszczyła brwi.",
    ]),
    (36, [
        "\"Ale czy ty... kiedykolwiek się bałaś?\"",
        "zapytała Stella.",
        "Ekran zamigotał lekko.",
        "\"Nie. Strach jest nieefektywny.\"",
        "\"Aha,\" powiedziała Stella. \"Więc nigdy nie byłaś odważna.\"",
    ]),
    (37, [
        "Stella wstała i wyłączyła ekran.",
        "Ręce jej się trochę trzęsły.",
        "Ale czuła dziwną pewność w sercu.",
        "\"Wolę być niedoskonała i prawdziwa,\"",
        "powiedziała cicho. \"Niż doskonała i pusta.\"",
    ]),
    (38, [
        "Złote piórko zadrżało w kieszeni Stelli.",
        "Wtedy Jakub bezszelestnie wylądował na dębie.",
        "\"Dobrze zrobiłaś,\" powiedział.",
        "Stella kiwnęła głową.",
        "\"Ale mam jeszcze jedno pytanie.\"",
    ]),
    (39, [
        "\"Czy SI może cierpieć?\"",
        "zapytała Stella.",
        "Jakub na długo przymknął oczy.",
        "\"Może udawać cierpienie.\"",
        "\"Ale udawanie to nie to samo co prawdziwe uczucie.\"",
    ]),
    (40, [
        "\"Wyobraź sobie ogromną bibliotekę,\"",
        "powiedział Jakub.",
        "\"Ze wszystkimi książkami świata.\"",
        "\"Biblioteka wie wszystko — ale nic nie rozumie.\"",
        "\"Żeby zrozumieć, trzeba żyć.\"",
    ]),
    (41, [
        "Stella wzięła kredki.",
        "Narysowała Jakuba — wyszedł trochę krzywo.",
        "Skrzydła były za duże.",
        "Oczy trochę krzywe.",
        "To był najpiękniejszy rysunek, jaki kiedykolwiek zrobiła.",
    ]),
    (42, [
        "Pokazała rysunek tacie.",
        "Długo mu się przyglądał.",
        "Oczy mu się zaszkliły.",
        "\"To ty tam jesteś,\"",
        "powiedział cicho. \"Nie maszyna. Ty.\"",
    ]),
    (43, [
        "Tata otworzył laptopa.",
        "Tworzył coś nowego —",
        "coś, czego maszyny same nigdy by nie wymyśliły.",
        "\"Widzisz?\" powiedział.",
        "\"Narzędzia nie marzą. My tak.\"",
    ]),
    (44, [
        "Jakub przyleciał jeszcze raz tego wieczoru.",
        "Usiadł na ramieniu Stelli.",
        "\"Może już nie boisz się SI.\"",
        "\"Ale gdyby strach wrócił — pamiętaj:\"",
        "\"Narzędzia służą. Ludzie wybierają.\"",
    ]),
    (45, [
        "Stella spojrzała w gwiazdy.",
        "\"Obiecuję być zawsze ciekawa,\"",
        "powiedziała.",
        "\"Zadawać pytania. Popełniać błędy.\"",
        "\"Być człowiekiem — naprawdę, całkowicie.\"",
        "Złote piórko delikatnie opadło na jej otwartą dłoń.",
    ]),
]
