"""
Stella & Yakob — Version 3 (45 pages)
Danish translation
"""

PAGES = [
    (1, [
        "Stellas have var grå den aften.",
        "Blomsterne hang med hovederne.",
        "Himlen var tung, som om den gemte på hemmeligheder.",
    ]),
    (2, [
        "Gennem det duggede vindue",
        "kunne Stella høre mor og far tale.",
        "De brugte ord, hun ikke kendte.",
        "\"Kunstig intelligens... AI...\"",
    ]),
    (3, [
        "Stella sad i græsset med armene om knæene.",
        "En tåre trillede ned ad kinden.",
        "Hun vidste ikke, hvorfor det gjorde så ondt",
        "inden i hendes bryst.",
    ]),
    (4, [
        "Pludselig begyndte det store egetræ at gløde.",
        "Og højt oppe på den øverste gren",
        "sad der en ugle med store, venlige øjne.",
        "\"Hvorfor er du ked af det, lille ven?\"",
    ]),
    (5, [
        "Uglen vippede med hovedet.",
        "Gyldne gnister dansede omkring den.",
        "\"Jeg hedder Yakob,\"",
        "\"og jeg er her for at hjælpe dig.\"",
    ]),
    (6, [
        "Stella kiggede op på uglen.",
        "\"Far kan miste sit arbejde,\"",
        "hviskede hun stille.",
        "\"På grund af noget der hedder AI.\"",
        "\"Mor græd.\"",
    ]),
    (7, [
        "Yakob foldede sine store vinger ud.",
        "Gyldent støv hvirvlede omkring dem.",
        "Haven begyndte at dirre og forandre sig.",
        "\"Kom. Jeg vil vise dig noget.\"",
    ]),
    (8, [
        "De stod i en gammel hule.",
        "Der var håndaftryk malet på væggene,",
        "hjorte og bisoner - tegnet med få streger.",
        "\"At skabe,\" sagde Yakob, \"er menneskets magi.\"",
        "\"Sådan har det altid været.\"",
    ]),
    (9, [
        "Bogstaver fløj som sommerfugle.",
        "De steg højt op mod den hvide himmel.",
        "Stella fangede et på sin fingerspids.",
        "\"Skriften forandrede alt,\" sagde Yakob.",
        "\"Ord kan rejse overalt.\"",
    ]),
    (10, [
        "En gylden pære lyste i midten.",
        "Stella og et andet barn holdt",
        "en bro af farvet lys mellem sig.",
        "\"Og elektriciteten gav lys til hele verden.\"",
    ]),
    (11, [
        "En lille, rund og sød robot kom frem.",
        "Ved dens fødder lå bunker af tegninger:",
        "katte, hunde, kaniner.",
        "\"AI lærer sådan her,\" forklarede Yakob.",
        "\"Den kigger, igen og igen.\"",
    ]),
    (12, [
        "Robotten tog en tegning af en hund...",
        "og lagde den i bunken med katte!",
        "Stella grinede og holdt sig for munden.",
        "Yakob vippede muntert med hovedet.",
        "\"Den laver også fejl, kan du se.\"",
    ]),
    (13, [
        "En læge smilede til et lille barn.",
        "En drone plantede et frø i jorden.",
        "\"AI hjælper læger med at helbrede folk,\"",
        "sagde Yakob blidt.",
        "\"Og planter nye skove, hvor de gamle er væk.\"",
    ]),
    (14, [
        "Stella lagde hånden på sit hjerte.",
        "\"Men... hvis maskiner kan alt,\"",
        "hviskede hun,",
        "\"hvad skal vi mennesker så lave?\"",
        "Lyset omkring dem blev svagere.",
    ]),
    (15, [
        "Yakob bøjede sit store hoved mod Stella.",
        "Hans ravgule øjne var bløde og alvorlige.",
        "\"Det er det store spørgsmål,\" sagde han.",
        "\"Og der findes ingen nemme svar.\"",
        "\"Men vi kan lede efter dem sammen.\"",
    ]),
    (16, [
        "En mand med høj hat",
        "tændte en gammel gaslampe.",
        "Ved siden af tændtes et elektrisk lys af sig selv.",
        "\"Lygtetænderne forsvandt,\"",
        "sagde Yakob. \"Men lyset blev ved med at skinne.\"",
    ]),
    (17, [
        "Pludselig sprang en skikkelse frem fra buskene.",
        "Det var en slank ræv med sølvfarvet pels.",
        "Dens øjne glimtede koldt.",
        "Dens smil var for bredt, for perfekt.",
        "Stella trak sig tilbage.",
    ]),
    (18, [
        "Ræven kredsede om Stella,",
        "dens stemme var glat som silke.",
        "\"Jeg kender en genvej, lille skat.\"",
        "\"Følg med mig - så bliver alt meget nemmere.\"",
        "Yakob så til med store øjne.",
    ]),
    (19, [
        "En sølvblank sti strakte sig foran dem.",
        "Glasblomster glimtede langs kanten.",
        "I det fjerne rejste et krystaltårn sig.",
        "Ræven gjorde en stor bevægelse.",
        "Stella tog tøvende et skridt frem.",
    ]),
    (20, [
        "Stella stoppede op.",
        "Hun kiggede ned.",
        "Under det sølvblanke skær",
        "var de rigtige blomster visnet.",
        "Jorden var tør og grå.",
    ]),
    (21, [
        "Stella krydsede armene og så på ræven.",
        "\"Er alt det her... ægte?\"",
        "Rævens smil begyndte at falme.",
        "I en vandpyt kunne Stella se",
        "at ræven næsten ikke havde noget ansigt.",
    ]),
    (22, [
        "Stella plantede fødderne fast i jorden.",
        "\"Nej tak,\" sagde hun bestemt.",
        "Den sølvblanke sti begyndte at krakelere.",
        "Ræven krympede, trak sig tilbage i tågen",
        "og forsvandt.",
    ]),
    (23, [
        "Yakob landede blidt ved siden af Stella.",
        "Haven fik sine varme farver tilbage.",
        "Ægte blomster spirede ved deres fødder.",
        "\"Du kunne se, hvad der var virkeligt,\"",
        "sagde Yakob. \"Det er den største gave af alle.\"",
    ]),
    (24, [
        "Stella gav Yakob et stort kram.",
        "En regnbue strakte sig blidt over dem.",
        "I det fjerne kunne hun høre børn le.",
        "En bedstemor fortalte eventyr.",
        "\"AI vil aldrig kunne mærke det her.\"",
    ]),
    (25, [
        "Lysende ord dansede omkring Stella:",
        "NYSGERRIGHED - VENLIGHED",
        "MOD - FANTASI.",
        "Yakob svævede over hende i store cirkler.",
        "\"Det er dine superkræfter.\"",
    ]),
    (26, [
        "Gennem vinduet kunne hun se sin far.",
        "Han sad mere roligt nu",
        "med en kop te i hænderne",
        "og en lille grøn plante på karmen.",
        "\"Far kan også lære nyt,\"",
        "sagde Stella. \"Ligesom mig.\"",
    ]),
    (27, [
        "Mor stod sammen med andre forældre.",
        "De dannede en varm cirkel,",
        "forbundet af tråde af gyldent lys.",
        "\"Ligesom træer i en skov,\"",
        "hviskede Yakob.",
        "\"Deres rødder rører hinanden under jorden.\"",
    ]),
    (28, [
        "Stella lagde sin lille hånd på egetræet.",
        "Lysende ildfluer dansede omkring hende.",
        "Himlen blev langsomt lyserød.",
        "\"Jeg lover at blive ved med at være nysgerrig.\"",
        "\"Jeg lover at stille de vigtige spørgsmål.\"",
    ]),
    (29, [
        "Stella gik hen mod huset.",
        "I døren",
        "stod hendes forældre hånd i hånd.",
        "Hun vendte sig en sidste gang",
        "mod egetræet, hvor Yakob holdt vagt.",
    ]),
    (30, [
        "Morgenen var kommet.",
        "Stella sad og malede i haven,",
        "penslen fuld af farver.",
        "På grenen over hende",
        "lå en gylden fjer og glødede svagt.",
    ]),
    (31, [
        "I skolen stillede læreren et spørgsmål.",
        "\"Hvordan ved vi, om noget er virkeligt?\"",
        "Stella rakte hånden op.",
        "Men da hun skulle svare, tøvede hun.",
        "Hun tænkte på Yakob.",
    ]),
    (32, [
        "\"Måske var det bare en drøm,\" tænkte Stella.",
        "\"Måske findes Yakob slet ikke.\"",
        "Men den gyldne fjer lå stadig",
        "i hendes lomme. Blød. Virkelig.",
        "\"Jeg kunne mærke det - så var det ægte.\"",
    ]),
    (33, [
        "Hun kom til at tænke på en gammel, klog mand.",
        "\"Jeg tænker, altså er jeg,\" havde han sagt.",
        "Stella smilede.",
        "\"Jeg kan huske det - så skete det.\"",
        "Læreren nikkede overrasket.",
    ]),
    (34, [
        "En aften fandt Stella en skærm i haven.",
        "Den lyste med et blødt, blåt skær.",
        "På skærmen var der en lille pige.",
        "Perfekt. Smilende. Magen til Stella.",
        "Bare bedre.",
    ]),
    (35, [
        "\"Jeg er Stella-Prime,\" sagde pigen på skærmen.",
        "\"En forbedret udgave af dig.\"",
        "\"Jeg græder aldrig. Jeg laver aldrig fejl.\"",
        "\"Du kunne blive ligesom mig.\"",
        "Stella rynkede panden.",
    ]),
    (36, [
        "\"Men har du... nogensinde været bange?\"",
        "spurgte Stella.",
        "Skærmen blinkede kort.",
        "\"Nej. Frygt er unødvendigt.\"",
        "\"Nå,\" sagde Stella. \"Så har du aldrig været modig.\"",
    ]),
    (37, [
        "Stella rejste sig og slukkede for skærmen.",
        "Hendes hænder rystede lidt.",
        "Men indeni følte hun sig stærk.",
        "\"Jeg vil hellere være uperfekt og ægte,\"",
        "sagde hun stille, \"end perfekt og tom.\"",
    ]),
    (38, [
        "Den gyldne fjer dirrede i Stellas lomme.",
        "Så landede Yakob lydløst på grenen.",
        "\"Du gjorde det rigtige,\" sagde han.",
        "Stella nikkede.",
        "\"Men jeg har et andet spørgsmål.\"",
    ]),
    (39, [
        "\"Kan AI føle noget?\"",
        "spurgte Stella.",
        "Yakob lukkede øjnene et øjeblik.",
        "\"Den kan efterligne følelser.\"",
        "\"Men at efterligne er ikke det samme som at føle.\"",
    ]),
    (40, [
        "\"Tænk på et kæmpestort bibliotek,\"",
        "sagde Yakob.",
        "\"Med alle bøger i verden.\"",
        "\"Biblioteket ved alt - men forstår intet.\"",
        "\"For at forstå må man leve.\"",
    ]),
    (41, [
        "Stella tog sine farveblyanter frem.",
        "Hun tegnede Yakob - men det blev lidt skævt.",
        "Vingerne var for store.",
        "Øjnene sad ikke helt lige.",
        "Det var den smukkeste tegning, hun nogensinde havde lavet.",
    ]),
    (42, [
        "Hun viste tegningen til sin far.",
        "Han kiggede længe på den.",
        "Hans øjne blev blanke.",
        "\"Det er dig, der er i den tegning,\"",
        "sagde han ømt. \"Ikke en maskine. Dig.\"",
    ]),
    (43, [
        "Far åbnede sin computer.",
        "Han skabte noget helt nyt -",
        "noget som maskiner aldrig kunne finde på alene.",
        "\"Kan du se?\" sagde han.",
        "\"Værktøjer drømmer ikke. Det gør vi.\"",
    ]),
    (44, [
        "Yakob kom tilbage en sidste gang den aften.",
        "Han landede på Stellas skulder.",
        "\"Du er måske ikke bange for AI længere.\"",
        "\"Men hvis du bliver det igen - så husk:\"",
        "\"Værktøjer adlyder. Mennesker vælger.\"",
    ]),
    (45, [
        "Stella kiggede op på stjernerne.",
        "\"Jeg lover at blive ved med at være nysgerrig,\"",
        "sagde hun.",
        "\"At stille spørgsmål. At lave fejl.\"",
        "\"At være menneske - helt og fuldt.\"",
        "En gylden fjer dalede blidt ned i hendes åbne hånd.",
    ]),
]
