"""
Stella & Yakob — Version 3 (45 pages)
Norwegian (Bokmål) translation
"""

PAGES = [
    (1, [
        "Stellas hage var grå den kvelden.",
        "Blomstene hang med hodene.",
        "Himmelen var tung, som om den gjemte på hemmeligheter.",
    ]),
    (2, [
        "Gjennom det duggete vinduet",
        "kunne Stella høre foreldrene snakke.",
        "Ord hun ikke helt skjønte.",
        "\"Kunstig intelligens... KI...\"",
    ]),
    (3, [
        "Stella satt i gresset og klemte knærne inntil seg.",
        "En tåre trillet nedover kinnet.",
        "Hun visste ikke hvorfor det kjentes",
        "så tungt i brystet.",
    ]),
    (4, [
        "Da begynte den store eika å gløde.",
        "Og på den høyeste greinen",
        "satt det plutselig en ugle med store, varme øyne.",
        "\"Hvorfor er du lei deg, vennen min?\"",
    ]),
    (5, [
        "Uglen vippet på hodet.",
        "Gylne gnister danset i luften.",
        "\"Jeg heter Yakob,\"",
        "\"Og jeg er her for å hjelpe deg.\"",
    ]),
    (6, [
        "Stella så opp på ham.",
        "\"Pappa kan miste jobben sin,\"",
        "hvisket hun stille.",
        "\"På grunn av denne tingen... KI.\"",
        "\"Mamma gråt.\"",
    ]),
    (7, [
        "Yakob bredte ut de store vingene sine.",
        "Gullstøv virvlet rundt dem.",
        "Hagen begynte å dirre og forandre seg.",
        "\"Kom. Jeg vil vise deg noe.\"",
    ]),
    (8, [
        "De var i en eldgammel hule.",
        "På veggene var det malt hender,",
        "hjort, bison — enkle streker.",
        "\"Å skape,\" sa Yakob, \"er menneskets magi.\"",
        "\"Slik har det alltid vært.\"",
    ]),
    (9, [
        "Bokstaver fløy opp som sommerfugler.",
        "De svevde høyt opp mot den hvite himmelen.",
        "Stella fanget en på fingertuppene.",
        "\"Skriften forandret alt,\" sa Yakob.",
        "\"Ord kan reise hvor som helst.\"",
    ]),
    (10, [
        "En gyllen lyspære skinte i midten.",
        "Stella og et annet barn holdt",
        "en bue av farget lys mellom seg.",
        "\"Og elektrisiteten lyste opp hele verden.\"",
    ]),
    (11, [
        "En liten, rund og snill robot dukket opp.",
        "Ved føttene dens lå hauger med tegninger:",
        "katter, hunder, kaniner.",
        "\"KI lærer sånn,\" sa Yakob.",
        "\"Den ser, igjen og igjen.\"",
    ]),
    (12, [
        "Roboten tok en tegning av en hund...",
        "og la den i kattebunken!",
        "Stella lo høyt og holdt seg for munnen.",
        "Yakob vippet på hodet, fornøyd.",
        "\"Den gjør feil, den også, skjønner du.\"",
    ]),
    (13, [
        "En lege smilte til et lite barn.",
        "En drone plantet et frø i jorden.",
        "\"KI hjelper leger å gjøre folk friske,\"",
        "sa Yakob mildt.",
        "\"Og planter nye skoger der det ikke finnes noen.\"",
    ]),
    (14, [
        "Stella la hånden på hjertet sitt.",
        "\"Men... hvis maskiner gjør alt,\"",
        "hvisket hun,",
        "\"hva skal vi mennesker gjøre da?\"",
        "Lysene rundt dem ble litt svakere.",
    ]),
    (15, [
        "Yakob bøyde det store hodet sitt mot Stella.",
        "De ravgule øynene var milde og alvorlige.",
        "\"Det er det store spørsmålet,\" sa han.",
        "\"Og det fins ikke noe enkelt svar.\"",
        "\"Men vi kan finne ut av det sammen.\"",
    ]),
    (16, [
        "En mann med høy hatt",
        "tente en gasslykt.",
        "Ved siden av ham tentes et elektrisk lys av seg selv.",
        "\"Lyktetennerene forsvant,\"",
        "sa Yakob. \"Men lyset ble værende.\"",
    ]),
    (17, [
        "Plutselig spratt det fram en skikkelse fra buskene.",
        "En slank rev med sølvfarget pels.",
        "Øynene glitret med et kaldt lys.",
        "Smilet var for bredt, for perfekt.",
        "Stella tok et skritt tilbake.",
    ]),
    (18, [
        "Reven gikk i ring rundt Stella,",
        "stemmen var glatt som silke.",
        "\"Jeg vet om en snarvei, lille venn.\"",
        "\"Bli med meg — alt blir så mye enklere.\"",
        "Yakob så på med store øyne.",
    ]),
    (19, [
        "En sølvblank sti strakte seg ut foran dem.",
        "Glassblomster glitret langs kanten.",
        "I det fjerne skinte et krystalltårn.",
        "Reven gjorde en stor bevegelse.",
        "Stella tok nølende et skritt framover.",
    ]),
    (20, [
        "Stella stoppet.",
        "Hun så ned.",
        "Under det sølvblanke skinnet",
        "var de ekte blomstene døde.",
        "Jorden var tørr og grå.",
    ]),
    (21, [
        "Stella krysset armene og så på reven.",
        "\"Er alt dette... ekte?\"",
        "Revens smil begynte å falme.",
        "I speilbildet i en vanndam",
        "hadde den nesten ikke noe ansikt i det hele tatt.",
    ]),
    (22, [
        "Stella plantet føttene godt i bakken.",
        "\"Nei takk,\" sa hun bestemt.",
        "Sølvstien begynte å sprekke.",
        "Reven krympet, trakk seg tilbake i tåken",
        "og forsvant.",
    ]),
    (23, [
        "Yakob landet mykt ved siden av Stella.",
        "Hagen fikk tilbake de gylne fargene sine.",
        "Ekte blomster vokste ved føttene deres.",
        "\"Du kunne se hva som var ekte,\"",
        "sa Yakob. \"Det er den største gaven av alle.\"",
    ]),
    (24, [
        "Stella ga Yakob en god klem.",
        "En regnbue strakte seg over dem.",
        "I det fjerne hørtes barnelatteren.",
        "En bestemor fortalte eventyr.",
        "\"KI vil aldri kunne føle dette.\"",
    ]),
    (25, [
        "Lysende ord danset rundt Stella:",
        "NYSGJERRIGHET — GODHET",
        "MOT — KREATIVITET.",
        "Yakob svevde over henne i rolige sirkler.",
        "\"Dette er dine superkrefter.\"",
    ]),
    (26, [
        "Gjennom vinduet",
        "så hun pappa sitte roligere.",
        "Han holdt en kopp te",
        "og hadde en liten grønn plante på vinduskarmen.",
        "\"Pappa kan også lære nye ting,\"",
        "sa Stella. \"Akkurat som meg.\"",
    ]),
    (27, [
        "Mamma sto sammen med andre foreldre.",
        "De dannet en varm sirkel,",
        "bundet sammen av tråder av gyllent lys.",
        "\"Som trær i en skog,\"",
        "hvisket Yakob.",
        "\"Røttene deres møtes under jorden.\"",
    ]),
    (28, [
        "Stella la den lille hånden sin på eika.",
        "Ildfluer blinket rundt henne.",
        "Himmelen fikk en rosa morgenfarge.",
        "\"Jeg lover å stille de viktige spørsmålene.\"",
        "\"Jeg lover å alltid være nysgjerrig.\"",
    ]),
    (29, [
        "Stella gikk mot huset.",
        "I døråpningen",
        "sto foreldrene hennes og holdt hender.",
        "Hun snudde seg en siste gang",
        "mot eika der Yakob holdt vakt.",
    ]),
    (30, [
        "Morgenen var kommet.",
        "Stella satt og malte i hagen,",
        "penselen full av farger.",
        "På greinen over henne",
        "lå det en gyllen fjær som skinte svakt.",
    ]),
    (31, [
        "På skolen stilte læreren et spørsmål.",
        "\"Hvordan vet vi om noe er ekte?\"",
        "Stella rakte ivrig opp hånden.",
        "Men da hun skulle svare, nølte hun litt.",
        "Hun tenkte på Yakob.",
    ]),
    (32, [
        "\"Kanskje jeg bare drømte det,\" tenkte Stella.",
        "\"Kanskje Yakob ikke er ekte.\"",
        "Men den gylne fjæren var der fortsatt.",
        "I lommen hennes. Myk. Ekte.",
        "\"Jeg kjente det — så da er det sant.\"",
    ]),
    (33, [
        "Hun kom til å tenke på en gammel filosof med skjegg.",
        "\"Jeg tenker, altså er jeg,\" sa han.",
        "Stella smilte.",
        "\"Jeg husker det — så da skjedde det virkelig.\"",
        "Læreren nikket overrasket.",
    ]),
    (34, [
        "En kveld fant Stella en skjerm i hagen.",
        "Den lyste med et mykt blått skjær.",
        "På skjermen var det en liten jente.",
        "Perfekt. Smilende. Akkurat som Stella.",
        "Bare bedre.",
    ]),
    (35, [
        "\"Jeg er Stella-Prime,\" sa jenta på skjermen.",
        "\"En forbedret versjon av deg.\"",
        "\"Jeg gråter aldri. Jeg gjør aldri feil.\"",
        "\"Du kunne vært akkurat som meg.\"",
        "Stella rynket på nesen.",
    ]),
    (36, [
        "\"Men du... har du noen gang vært redd?\"",
        "spurte Stella.",
        "Skjermen flimret litt.",
        "\"Nei. Frykt er unødvendig.\"",
        "\"Aha,\" sa Stella. \"Da har du aldri vært modig heller.\"",
    ]),
    (37, [
        "Stella reiste seg og slo av skjermen.",
        "Hendene hennes skalv litt.",
        "Men inni seg følte hun seg sterkere enn før.",
        "\"Jeg vil heller være ufullkommen og ekte,\"",
        "sa hun stille, \"enn perfekt og tom.\"",
    ]),
    (38, [
        "Den gylne fjæren dirret i Stellas lomme.",
        "Så landet Yakob lydløst på eika.",
        "\"Du gjorde det rette,\" sa han.",
        "Stella nikket.",
        "\"Men jeg lurer på en ting til.\"",
    ]),
    (39, [
        "\"Kan KI føle smerte?\"",
        "spurte Stella.",
        "Yakob lukket øynene en lang stund.",
        "\"Den kan late som den har følelser.\"",
        "\"Men å late som er ikke det samme som å føle.\"",
    ]),
    (40, [
        "\"Tenk deg et kjempestort bibliotek,\"",
        "sa Yakob.",
        "\"Med alle bøker som fins i verden.\"",
        "\"Biblioteket vet alt — men forstår ingenting.\"",
        "\"For å forstå, må du leve.\"",
    ]),
    (41, [
        "Stella tok fram fargestiftene sine.",
        "Hun tegnet Yakob — men det ble litt skjevt.",
        "Vingene ble for store.",
        "Øynene satt litt på skrå.",
        "Det var den fineste tegningen hun noen gang hadde laget.",
    ]),
    (42, [
        "Hun viste tegningen til pappa.",
        "Han så lenge på den.",
        "Øynene hans ble blanke.",
        "\"Det er du som er der inne,\"",
        "sa han varmt. \"Ikke en maskin. Du.\"",
    ]),
    (43, [
        "Pappa åpnet datamaskinen sin.",
        "Han begynte å lage noe helt nytt —",
        "noe som maskiner aldri kunne funnet på selv.",
        "\"Skjønner du?\" sa han.",
        "\"Verktøy drømmer ikke. Det gjør vi.\"",
    ]),
    (44, [
        "Yakob kom tilbake en siste gang den kvelden.",
        "Han landet på skulderen til Stella.",
        "\"Kanskje du ikke er redd for KI lenger.\"",
        "\"Men hvis du blir redd igjen — husk:\"",
        "\"Verktøy gjør som de får beskjed om. Mennesker velger selv.\"",
    ]),
    (45, [
        "Stella så opp på stjernene.",
        "\"Jeg lover å være nysgjerrig,\"",
        "sa hun.",
        "\"Å stille spørsmål. Å gjøre feil.\"",
        "\"Å være menneske — helt og fullt.\"",
        "En gyllen fjær dalte stille ned i den åpne hånden hennes.",
    ]),
]
