PAGES = [
    (1, [
        "O akşam Stella'nın bahçesi griydi.",
        "Çiçekler başlarını eğmişti.",
        "Gökyüzü ağırdı, sanki sırlarla doluydu.",
    ]),
    (2, [
        "Buğulu pencereden",
        "Stella anne babasının konuşmalarını duyabiliyordu.",
        "Anlamadığı kelimeler.",
        "\"Yapay zeka... AI...\"",
    ]),
    (3, [
        "Stella çimlere oturdu, dizlerini kendine çekti.",
        "Bir damla gözyaşı yanağından süzüldü.",
        "Neden içinde bir şeyin",
        "bu kadar sıkıştığını bilmiyordu.",
    ]),
    (4, [
        "Sonra büyük meşe ağacı hafifçe parıldadı.",
        "Ve en yüksek dalında,",
        "yuvarlak, sıcacık gözlü bir baykuş belirdi.",
        "\"Neden üzgünsün, canım?\"",
    ]),
    (5, [
        "Baykuş başını yana eğdi.",
        "Altın kıvılcımlar havada dans etti.",
        "\"Benim adım Yakup.\"",
        "\"Ve senin için buradayım.\"",
    ]),
    (6, [
        "Stella ona baktı.",
        "\"Babam işini kaybedebilir,\"",
        "diye fısıldadı.",
        "\"Bu şey yüzünden... AI.\"",
        "\"Annem ağladı.\"",
    ]),
    (7, [
        "Yakup kocaman kanatlarını açtı.",
        "Altın tozlar etraflarında döndü.",
        "Bahçe titreyip değişti.",
        "\"Gel. Sana bir şey göstereceğim.\"",
    ]),
    (8, [
        "Kendilerini eski bir mağarada buldular.",
        "Duvarlarda insan elleri,",
        "geyikler, bizonlar — kabaca çizilmiş.",
        "\"Yaratmak,\" dedi Yakup, \"insanların büyüsüdür.\"",
        "\"Hep öyle olmuştur.\"",
    ]),
    (9, [
        "Harfler kelebekler gibi uçuştu.",
        "Beyaz gökyüzüne doğru süzüldüler.",
        "Stella parmak ucuyla birini yakaladı.",
        "\"Yazı her şeyi değiştirdi,\" dedi Yakup.",
        "\"Kelimeler artık her yere ulaşabilir.\"",
    ]),
    (10, [
        "Ortada altın bir ampul parlıyordu.",
        "Stella ve başka bir çocuk",
        "aralarında renkli bir ışık huzmesi tutuyordu.",
        "\"Ve elektrik tüm dünyayı aydınlattı.\"",
    ]),
    (11, [
        "Minik, yuvarlak, sevimli bir robot belirdi.",
        "Ayaklarının dibinde çizim yığınları:",
        "kediler, köpekler, tavşanlar.",
        "\"AI böyle öğrenir,\" dedi Yakup.",
        "\"Tekrar tekrar bakarak.\"",
    ]),
    (12, [
        "Robot bir köpek çizimini kaptı...",
        "ve onu kedi yığınına koydu!",
        "Stella kahkahalarla güldü, elini ağzına götürdü.",
        "Yakup gülümseyerek başını yana eğdi.",
        "\"O da hata yapıyor, gördün mü?\"",
    ]),
    (13, [
        "Bir doktor küçük bir çocuğa gülümsedi.",
        "Bir drone toprağa tohum ekti.",
        "\"AI doktorlara hastalıkları iyileştirmekte yardım eder,\"",
        "dedi Yakup sevecenlikle.",
        "\"Ve kimsenin ulaşamadığı yerlerde ormanlar yetiştirir.\"",
    ]),
    (14, [
        "Stella elini kalbine koydu.",
        "\"Ama... makineler her şeyi yaparsa,\"",
        "diye fısıldadı,",
        "\"insanlar ne işe yarar?\"",
        "Etraflarındaki ışıklar hafifçe söndü.",
    ]),
    (15, [
        "Yakup kocaman başını Stella'ya doğru eğdi.",
        "Kehribar gözleri yumuşak ve ciddiydi.",
        "\"İşte asıl soru bu,\" dedi.",
        "\"Ve kolay bir cevabı yok.\"",
        "\"Ama birlikte düşünebiliriz.\"",
    ]),
    (16, [
        "Bir adam silindir şapkasıyla",
        "gaz lambasını yakıyordu.",
        "Yanında, elektrikli bir lamba kendiliğinden yandı.",
        "\"Lambacılar artık yok,\"",
        "dedi Yakob. \"Ama ışık hep var.\"",
    ]),
    (17, [
        "Aniden, çalıların arasından bir şekil belirdi.",
        "Gümüş tüylü, zarif bir tilki.",
        "Gözleri soğuk bir ışıkla parlıyordu.",
        "Gülümsemesi fazla geniş, fazla kusursuzdu.",
        "Stella bir adım geriye çekildi.",
    ]),
    (18, [
        "Tilki Stella'nın etrafında döndü,",
        "sesi ipek gibi yumuşaktı.",
        "\"Sana kısa bir yol gösterebilirim, küçük kız.\"",
        "\"Benimle gel — her şey çok daha kolay olacak.\"",
        "Yakob izledi, gözleri kocaman.",
    ]),
    (19, [
        "Önlerinde gümüşi bir yol uzanıyordu.",
        "Kenarlarda cam çiçekler ışıldıyordu.",
        "Uzakta, kristal bir kule parlıyordu.",
        "Tilki gösterişli bir hareketle işaret etti.",
        "Stella tereddütle bir adım attı.",
    ]),
    (20, [
        "Stella duraksadı.",
        "Aşağıya baktı.",
        "Gümüş parıltının altında,",
        "gerçek çiçekler solmuştu.",
        "Toprak kurumuş ve cansızdı.",
    ]),
    (21, [
        "Stella kollarını kavuşturup tilkiye baktı.",
        "\"Bunların hepsi... gerçek mi?\"",
        "Tilkinin gülümsemesi titredi.",
        "Bir su birikintisinin yansımasında,",
        "yüzü neredeyse görünmüyordu.",
    ]),
    (22, [
        "Stella ayaklarını yere sağlam bastı.",
        "\"Hayır, teşekkür ederim,\" dedi kararlılıkla.",
        "Gümüş yol çatladı.",
        "Tilki küçüldü, sisin içinde kayboldu,",
        "ve yok oldu.",
    ]),
    (23, [
        "Yakob usulca Stella'nın yanına kondu.",
        "Bahçe yeniden altın rengine büründü.",
        "Ayaklarının dibinde gerçek çiçekler açtı.",
        "\"Gerçeği görebildin,\"",
        "dedi Yakob. \"Bu en değerli armağan.\"",
    ]),
    (24, [
        "Stella Yakob'a sıkıca sarıldı.",
        "Üzerlerinde nazikçe bir gökkuşağı belirdi.",
        "Uzaktan çocuk sesleri geliyordu.",
        "Bir nine masal anlatıyordu.",
        "\"Yapay zeka bunu asla hissedemez.\"",
    ]),
    (25, [
        "Parlak kelimeler Stella'nın etrafında dans etti:",
        "MERAK — SEVGİ",
        "CESARET — YARATICILIK.",
        "Yakob onun üzerinde yavaşça süzüldü.",
        "\"Bunlar senin süper güçlerin.\"",
    ]),
    (26, [
        "Pencerenin ardında,",
        "Baba daha huzurlu görünüyordu.",
        "Elinde bir fincan çay,",
        "pencere kenarında minik bir yeşil bitki.",
        "\"Babam da öğrenebilir,\"",
        "dedi Stella. \"Tıpkı benim gibi.\"",
    ]),
    (27, [
        "Anne diğer anne babalarla birlikteydi.",
        "Sıcacık bir halka oluşturmuşlardı,",
        "altın ışık iplikleriyle bağlanmış.",
        "\"Bir orman gibi hep beraber,\"",
        "diye fısıldadı Yakob.",
        "\"Kökler toprak altında birbirine dokunur.\"",
    ]),
    (28, [
        "Stella küçük elini meşe ağacına koydu.",
        "Ateşböcekleri çevresinde dans etti.",
        "Gökyüzü şafak pembesiyle aydınlanıyordu.",
        "\"Doğru soruları sormaya söz veriyorum.\"",
        "\"Hep meraklı kalmaya söz veriyorum.\"",
    ]),
    (29, [
        "Stella eve doğru yürüdü.",
        "Kapıda,",
        "anne babası el ele tutuşuyordu.",
        "Son bir kez dönüp baktı",
        "Yakob'un beklediği meşe ağacına.",
    ]),
    (30, [
        "Sabah olmuştu.",
        "Stella bahçede resim yapıyordu,",
        "fırçası rengarenkti.",
        "Üstündeki dalda,",
        "altın bir tüy usulca parlıyordu.",
    ]),
    (31, [
        "Okulda, öğretmen bir soru sordu.",
        "\"Bir şeyin gerçek olduğunu nasıl anlarız?\"",
        "Stella'nın eli havaya kalktı.",
        "Ama kelimeleri ararken duraksadı.",
        "Yakob'u düşünüyordu.",
    ]),
    (32, [
        "\"Belki hayal gördüm,\" diye düşündü Stella.",
        "\"Belki Yakob gerçek değil.\"",
        "Ama altın tüy hâlâ oradaydı.",
        "Cebinde. Yumuşacık. Gerçek.",
        "\"Dokundum — o yüzden gerçek.\"",
    ]),
    (33, [
        "Aklına sakallı bir filozof geldi.",
        "\"Düşünüyorum, öyleyse varım,\" diyordu.",
        "Stella gülümsedi.",
        "\"Hatırlıyorum — demek ki gerçekten oldu.\"",
        "Öğretmen başını salladı, şaşırmıştı.",
    ]),
    (34, [
        "Bir akşam, Stella bahçede bir ekran buldu.",
        "Yumuşak mavi bir ışıkla parlıyordu.",
        "Ekranda: küçük bir kız vardı.",
        "Kusursuz. Gülümseyen. Tıpkı Stella gibi.",
        "Ama daha mükemmel.",
    ]),
    (35, [
        "\"Ben Stella-Prime,\" dedi ekrandaki kız.",
        "\"Senin geliştirilmiş versiyonunum.\"",
        "\"Hiç ağlamam. Hiç hata yapmam.\"",
        "\"Sen de benim gibi olabilirsin.\"",
        "Stella kaşlarını çattı.",
    ]),
    (36, [
        "\"Peki sen... hiç korktun mu?\"",
        "diye sordu Stella.",
        "Ekran duraksadı. Hafifçe titredi.",
        "\"Hayır. Korku verimsizdir.\"",
        "\"Ah,\" dedi Stella. \"O zaman hiç cesur olmamışsın.\"",
    ]),
    (37, [
        "Stella ayağa kalktı ve ekranı kapattı.",
        "Elleri biraz titriyordu.",
        "Ama içinde garip bir güç hissetti.",
        "\"Kusursuz ve boş olmaktansa,",
        "kusurlu ve gerçek olmayı tercih ederim,\" dedi kendi kendine.",
    ]),
    (38, [
        "Altın tüy Stella'nın cebinde titredi.",
        "Ardından Yakob sessizce meşe ağacına kondu.",
        "\"Doğru olanı yaptın,\" dedi.",
        "Stella başını salladı.",
        "\"Ama sana başka bir sorum var.\"",
    ]),
    (39, [
        "\"Yapay zekâ acı çekebilir mi?\"",
        "diye sordu Stella.",
        "Yakob uzun bir süre gözlerini kapattı.",
        "\"Acı çekiyormuş gibi yapabilir.\"",
        "\"Ama taklit etmek, hissetmekle aynı şey değil.\"",
    ]),
    (40, [
        "\"Kocaman bir kütüphane düşün,\"",
        "dedi Yakob.",
        "\"Dünyadaki bütün kitaplarla dolu.\"",
        "\"Kütüphane her şeyi bilir — ama hiçbir şeyi anlamaz.\"",
        "\"Anlamak için yaşamak gerekir.\"",
    ]),
    (41, [
        "Stella boyalarını çıkardı.",
        "Yakob'u çizdi — ama biraz yamuk oldu.",
        "Kanatları çok büyük çıktı.",
        "Gözleri hafif şaşı duruyordu.",
        "Hayatında yaptığı en güzel resimdi.",
    ]),
    (42, [
        "Resmi babasına gösterdi.",
        "Uzun uzun baktı.",
        "Gözleri parladı.",
        "\"İşte bu sensin,\"",
        "dedi usulca. \"Bir makine değil. Sen.\"",
    ]),
    (43, [
        "Baba dizüstü bilgisayarını açtı.",
        "Makinelerin kendi başlarına asla hayal edemeyeceği",
        "yepyeni bir şey yaratıyordu.",
        "\"Anlıyor musun?\" dedi.",
        "\"Araçlar hayal kurmaz. Biz kurarız.\"",
    ]),
    (44, [
        "Yakob o akşam son kez geldi.",
        "Stella'nın omzuna kondu.",
        "\"Artık yapay zekâdan korkmana gerek yok.\"",
        "\"Ama korku geri gelirse — unutma:\"",
        "\"Araçlar hizmet eder. İnsanlar seçer.\"",
    ]),
    (45, [
        "Stella yıldızlara baktı.",
        "\"Hep meraklı kalacağıma söz veriyorum,\"",
        "dedi.",
        "\"Soru sormaya devam edeceğim. Hata yapmaktan korkmayacağım.\"",
        "\"İnsan olacağım — gerçekten, bütünüyle.\"",
        "Altın bir tüy usulca açık avucuna düştü.",
    ]),
]
