# German text for all 30 pages of Stella & Yakob v2

PAGES = [
    (1, [
        "Stellas Garten war an jenem Abend grau.",
        "Die Blumen hingen die Köpfe.",
        "Der Himmel war schwer, als wäre er voll Geheimnisse.",
    ]),
    (2, [
        "Durch das beschlagene Fenster",
        "hörte Stella ihre Eltern sprechen.",
        "Worte, die sie nicht verstand.",
        "«Künstliche Intelligenz… KI…»",
    ]),
    (3, [
        "Stella saß im Gras und umschlang ihre Knie.",
        "Eine Träne rollte ihre Wange hinunter.",
        "Sie wusste nicht, warum sich etwas",
        "so fest in ihrer Brust zusammenzog.",
    ]),
    (4, [
        "Da leuchtete die große Eiche sanft auf.",
        "Und auf dem höchsten Ast",
        "erschien eine Eule mit runden, warmen Augen.",
        "«Warum bist du traurig, meine Liebe?»",
    ]),
    (5, [
        "Die Eule neigte den Kopf.",
        "Goldene Funken tanzten in der Luft.",
        "«Ich heiße Yakob.»",
        "«Und ich bin für dich da.»",
    ]),
    (6, [
        "Stella schaute zu ihm hoch.",
        "«Papa könnte seine Arbeit verlieren»,",
        "sagte sie ganz leise.",
        "«Wegen dieser Sache… der KI.»",
        "«Mama hat geweint.»",
    ]),
    (7, [
        "Yakob breitete seine großen Flügel aus.",
        "Goldener Staub wirbelte um sie herum.",
        "Der Garten schien zu zittern und sich zu verwandeln.",
        "«Komm. Lass mich dir etwas zeigen.»",
    ]),
    (8, [
        "Sie befanden sich in einer alten Höhle.",
        "Menschliche Hände waren auf die Wände gemalt,",
        "Hirsche, Bisons — kaum skizziert.",
        "«Erschaffen», sagte Yakob, «ist die Magie der Menschen.»",
        "«Das war schon immer so.»",
    ]),
    (9, [
        "Buchstaben flogen wie Schmetterlinge davon.",
        "Sie stiegen hoch in den weißen Himmel.",
        "Stella fing einen mit den Fingerspitzen.",
        "«Die Schrift hat alles verändert», sagte Yakob.",
        "«Worte können überallhin reisen.»",
    ]),
    (10, [
        "Eine goldene Glühbirne leuchtete in der Mitte.",
        "Stella und ein anderes Kind hielten",
        "ein buntes Lichtband zwischen sich.",
        "«Und die Elektrizität hat die ganze Welt erleuchtet.»",
    ]),
    (11, [
        "Ein kleiner, runder, sanfter Roboter erschien.",
        "Zu seinen Füßen stapelten sich Zeichnungen:",
        "Katzen, Hunde, Hasen.",
        "«KI lernt so», sagte Yakob.",
        "«Sie schaut immer wieder hin.»",
    ]),
    (12, [
        "Der Roboter griff nach der Zeichnung eines Hundes…",
        "und legte sie auf den Stapel der Katzen!",
        "Stella prustete los, die Hand vor dem Mund.",
        "Yakob neigte den Kopf, belustigt.",
        "«Sie macht auch Fehler, siehst du.»",
    ]),
    (13, [
        "Ein Arzt lächelte ein kleines Kind an.",
        "Eine Drohne pflanzte einen Samen in die Erde.",
        "«KI hilft Ärzten beim Heilen»,",
        "sagte Yakob sanft.",
        "«Und pflanzt Wälder, wo keine mehr sind.»",
    ]),
    (14, [
        "Stella legte die Hand auf ihre Brust.",
        "«Aber… wenn Maschinen alles tun»,",
        "flüsterte sie,",
        "«wozu sind Menschen dann da?»",
        "Die Lichter um sie herum wurden etwas dunkler.",
    ]),
    (15, [
        "Yakob senkte seinen großen Kopf zu Stella.",
        "Seine bernsteinfarbenen Augen waren sanft und ernst.",
        "«Das ist die wahre Frage», sagte er.",
        "«Und es gibt keine einfache Antwort.»",
        "«Aber gemeinsam können wir suchen.»",
    ]),
    (16, [
        "Ein Mann mit Zylinderhut",
        "entzündete eine Gaslaterne.",
        "Daneben schaltete sich eine elektrische Lampe von selbst ein.",
        "«Die Laternenanzünder verschwanden»,",
        "sagte Yakob. «Aber das Licht blieb.»",
    ]),
    (17, [
        "Plötzlich schoss eine Gestalt aus den Büschen.",
        "Ein eleganter Fuchs mit silbernem Fell.",
        "Seine Augen glitzerten kalt.",
        "Sein Lächeln war zu breit, zu perfekt.",
        "Stella trat einen Schritt zurück.",
    ]),
    (18, [
        "Der Fuchs kreiste um Stella herum,",
        "seine Stimme weich wie Seide.",
        "«Ich kenne eine Abkürzung, Kleine.»",
        "«Komm mit mir — alles wird einfacher.»",
        "Yakob beobachtete ihn, die Augen weit geöffnet.",
    ]),
    (19, [
        "Ein silberner Weg erstreckte sich vor ihnen.",
        "Gläserne Blumen funkelten an den Rändern.",
        "In der Ferne glitzerte ein Kristallturm.",
        "Der Fuchs gestikulierte großartig.",
        "Stella machte zögernd einen Schritt vorwärts.",
    ]),
    (20, [
        "Stella hielt inne.",
        "Sie schaute nach unten.",
        "Unter dem silbernen Glanz",
        "waren die echten Blumen tot.",
        "Die Erde war rissig und bleich.",
    ]),
    (21, [
        "Stella verschränkte die Arme und schaute den Fuchs an.",
        "«Ist das alles… echt?»",
        "Das Lächeln des Fuchses schwankte.",
        "Im Spiegelbild einer Pfütze",
        "hatte er fast kein Gesicht mehr.",
    ]),
    (22, [
        "Stella stellte ihre Füße fest in die Erde.",
        "«Nein danke», sagte sie klar.",
        "Der silberne Weg bekam Risse.",
        "Der Fuchs schrumpfte, zog sich in den Nebel zurück",
        "und verschwand.",
    ]),
    (23, [
        "Yakob landete sanft neben Stella.",
        "Der Garten fand seine goldenen Farben wieder.",
        "Echte Blumen wuchsen zu ihren Füßen.",
        "«Du konntest sehen, was wirklich war»,",
        "sagte Yakob. «Das ist das größte Geschenk.»",
    ]),
    (24, [
        "Stella umarmte Yakob fest.",
        "Ein Regenbogen spannte sich sanft über sie.",
        "In der Ferne lachten Kinder.",
        "Eine Großmutter erzählte eine Geschichte.",
        "«Das wird KI niemals fühlen.»",
    ]),
    (25, [
        "Leuchtende Worte tanzten um Stella herum:",
        "NEUGIER — FREUNDLICHKEIT",
        "MUT — KREATIVITÄT.",
        "Yakob kreiste langsam über ihr.",
        "«Das sind deine Superkräfte.»",
    ]),
    (26, [
        "Durch das Fenster",
        "saß Papa ruhiger als zuvor.",
        "Eine Tasse Tee in den Händen,",
        "eine kleine grüne Pflanze auf dem Fensterbrett.",
        "«Papa kann auch lernen»,",
        "sagte Stella. «Genau wie ich.»",
    ]),
    (27, [
        "Mama war von anderen Eltern umgeben.",
        "Sie standen in einem warmen Kreis,",
        "verbunden durch Fäden aus goldenem Licht.",
        "«Zusammen wie ein Wald»,",
        "flüsterte Yakob.",
        "«Die Wurzeln berühren sich unter der Erde.»",
    ]),
    (28, [
        "Stella legte ihre kleine Hand auf die Eiche.",
        "Glühwürmchen leuchteten um sie herum auf.",
        "Der Himmel nahm die Farben des Morgenrots an.",
        "«Ich verspreche, die richtigen Fragen zu stellen.»",
        "«Ich verspreche, neugierig zu bleiben.»",
    ]),
    (29, [
        "Stella ging auf das Haus zu.",
        "Im Türrahmen",
        "hielten ihre Eltern sich an den Händen.",
        "Sie drehte sich ein letztes Mal um",
        "nach der Eiche, wo Yakob Wacht hielt.",
    ]),
    (30, [
        "Der Morgen war gekommen.",
        "Stella malte im Garten,",
        "den Pinsel voller Farben.",
        "Auf dem Ast über ihr",
        "leuchtete eine goldene Feder sanft.",
    ]),
]
