# French text for all 30 pages of Stella et Yakob v2
# Format: list of (page_num, lines_list)
# "" = half-line gap between dialogue sections

PAGES = [
    (1, [
        "Le jardin de Stella était gris ce soir-là.",
        "Les fleurs penchaient la tête.",
        "Le ciel était lourd, comme chargé de secrets.",
    ]),
    (2, [
        "Par la fenêtre embuée,",
        "Stella entendait ses parents parler.",
        "Des mots qu'elle ne comprenait pas.",
        "« Intelligence artificielle… IA… »",
    ]),
    (3, [
        "Stella s'assit dans l'herbe, les genoux serrés.",
        "Une larme roula sur sa joue.",
        "Elle ne savait pas pourquoi ça serrait",
        "si fort dans sa poitrine.",
    ]),
    (4, [
        "Alors le grand chêne brilla doucement.",
        "Et sur la branche la plus haute,",
        "apparut un hibou aux yeux ronds et chauds.",
        "« Pourquoi es-tu triste, ma chère ? »",
    ]),
    (5, [
        "L'hibou pencha la tête.",
        "Des étincelles dorées dansèrent dans l'air.",
        "« Je m'appelle Yakob. »",
        "« Et je suis là pour toi. »",
    ]),
    (6, [
        "Stella leva les yeux vers lui.",
        "« Papa risque de perdre son travail »,",
        "dit-elle tout doucement.",
        "« À cause de cette chose… l'IA. »",
        "« Maman a pleuré. »",
    ]),
    (7, [
        "Yakob déploya ses grandes ailes.",
        "Une poussière dorée tourbillonna autour d'eux.",
        "Le jardin sembla frémir et se transformer.",
        "« Viens. Laisse-moi te montrer quelque chose. »",
    ]),
    (8, [
        "Ils se retrouvèrent dans une grotte ancienne.",
        "Des mains humaines étaient dessinées sur les parois,",
        "des cerfs, des bisons — à peine esquissés.",
        "« Créer, dit Yakob, c'est la magie des humains. »",
        "« Depuis toujours. »",
    ]),
    (9, [
        "Des lettres s'envolèrent comme des papillons.",
        "Elles montèrent très haut dans le ciel blanc.",
        "Stella en attrapa une du bout des doigts.",
        "« L'écriture, dit Yakob, a tout changé. »",
        "« Les mots peuvent voyager partout. »",
    ]),
    (10, [
        "Une ampoule dorée brilla au centre.",
        "Stella et un autre enfant tenaient",
        "un ruban de lumière colorée entre eux.",
        "« Et l'électricité a allumé le monde entier. »",
    ]),
    (11, [
        "Un petit robot rond et doux apparut.",
        "À ses pieds, des piles de dessins :",
        "des chats, des chiens, des lapins.",
        "« L'IA apprend comme ça, dit Yakob. »",
        "« Elle regarde, encore et encore. »",
    ]),
    (12, [
        "Le robot attrapa le dessin d'un chien…",
        "et le posa dans la pile des chats !",
        "Stella éclata de rire, la main sur la bouche.",
        "Yakob inclina la tête, amusé.",
        "« Elle se trompe aussi, tu vois. »",
    ]),
    (13, [
        "Un médecin souriait à un petit enfant.",
        "Un drone déposait une graine dans la terre.",
        "« L'IA aide les médecins à soigner, »",
        "dit Yakob doucement.",
        "« Et plante des forêts là où il n'y en a plus. »",
    ]),
    (14, [
        "Stella posa la main sur sa poitrine.",
        "« Mais… si les machines font tout, »",
        "dit-elle tout bas,",
        "« à quoi servent les gens ? »",
        "Les lumières autour d'elles s'assombrirent un peu.",
    ]),
    (15, [
        "Yakob baissa sa grande tête vers Stella.",
        "Ses yeux ambrés étaient doux et graves.",
        "« C'est la vraie question, dit-il. »",
        "« Et il n'y a pas de réponse facile. »",
        "« Mais ensemble, on peut chercher. »",
    ]),
    (16, [
        "Un homme en chapeau haut-de-forme",
        "allumait un réverbère à gaz.",
        "À côté, une lampe électrique s'allumait seule.",
        "« Les allumeurs de réverbères ont disparu, »",
        "dit Yakob. « Mais la lumière est restée. »",
    ]),
    (17, [
        "Soudain, des buissons surgit une silhouette.",
        "Un renard élégant, à la fourrure argentée.",
        "Ses yeux brillaient d'un éclat froid.",
        "Son sourire était trop large, trop parfait.",
        "Stella recula d'un pas.",
    ]),
    (18, [
        "Le renard tournait autour de Stella,",
        "sa voix douce comme de la soie.",
        "« Je connais un raccourci, petite. »",
        "« Viens avec moi — tout sera plus simple. »",
        "Yakob regardait, les yeux grands ouverts.",
    ]),
    (19, [
        "Un chemin argenté s'étendait devant elles.",
        "Des fleurs de verre scintillaient sur les bords.",
        "Au loin, une tour de cristal étincelait.",
        "Le renard gesticula avec grandeur.",
        "Stella fit un pas en avant, hésitante.",
    ]),
    (20, [
        "Stella s'arrêta.",
        "Elle baissa les yeux.",
        "Sous l'éclat argenté,",
        "les vraies fleurs étaient mortes.",
        "La terre était craquelée et pâle.",
    ]),
    (21, [
        "Stella croisa les bras et regarda le renard.",
        "« Tout ça… c'est vrai ? »",
        "Le sourire du renard vacilla.",
        "Dans le reflet d'une flaque,",
        "il n'avait presque plus de visage.",
    ]),
    (22, [
        "Stella planta ses pieds dans la terre.",
        "« Non merci », dit-elle clairement.",
        "Le chemin argenté se fissura.",
        "Le renard rétrécit, recula dans la brume,",
        "et disparut.",
    ]),
    (23, [
        "Yakob se posa doucement près de Stella.",
        "Le jardin retrouva ses teintes dorées.",
        "De vraies fleurs poussèrent à leurs pieds.",
        "« Tu as su voir ce qui était réel, »",
        "dit Yakob. « C'est le plus grand des talents. »",
    ]),
    (24, [
        "Stella serra Yakob dans ses bras.",
        "Un arc-en-ciel s'étira doucement au-dessus d'eux.",
        "Au loin, des enfants riaient.",
        "Une grand-mère racontait une histoire.",
        "« L'IA ne ressentira jamais ça. »",
    ]),
    (25, [
        "Des mots lumineux dansèrent autour de Stella :",
        "CURIOSITÉ — GENTILLESSE",
        "COURAGE — CRÉATIVITÉ.",
        "Yakob plana au-dessus d'elle en cercles lents.",
        "« Ce sont tes superpouvoirs. »",
    ]),
    (26, [
        "Par la fenêtre,",
        "papa était assis plus calmement.",
        "Une tasse de thé dans les mains,",
        "une petite plante verte sur le rebord.",
        "« Papa peut apprendre aussi, »",
        "dit Stella. « Comme moi. »",
    ]),
    (27, [
        "Maman était entourée d'autres parents.",
        "Ils se tenaient dans un cercle chaleureux,",
        "reliés par des fils de lumière dorée.",
        "« Ensemble comme une forêt, »",
        "murmura Yakob.",
        "« Les racines se touchent sous la terre. »",
    ]),
    (28, [
        "Stella posa sa petite main sur le chêne.",
        "Des lucioles s'allumèrent autour d'elle.",
        "Le ciel prenait les roses de l'aube.",
        "« Je promets de poser les bonnes questions. »",
        "« Je promets de rester curieuse. »",
    ]),
    (29, [
        "Stella marcha vers la maison.",
        "Dans l'embrasure de la porte,",
        "ses parents se tenaient par la main.",
        "Elle se retourna une dernière fois",
        "vers le chêne où Yakob veillait.",
    ]),
    (30, [
        "Le matin était arrivé.",
        "Stella peignait dans le jardin,",
        "le pinceau plein de couleurs.",
        "Sur la branche au-dessus d'elle,",
        "une plume dorée brillait doucement.",
    ]),
]
